language: java
matrix:
  include:
    - os: linux
      dist: focal
      arch: amd64
      jdk: oraclejdk11
    - os: linux
      dist: focal
      arch: amd64
      jdk: openjdk11
    - os: linux
      dist: focal
      arch: arm64
      jdk: openjdk11
    - os: linux
      dist: focal
      arch: ppc64le
      jdk: openjdk11
    - os: linux
      dist: focal
      arch: s390x
      jdk: openjdk11
#    - os: windows
#      jdk: openjdk11
#    - os: windows
#      jdk: oraclejdk11
sudo: false
cache:
  directories:
  - $HOME/.m2