language: java
addons:
  apt:
    packages: maven
matrix:
  include:
    - os: linux
      dist: focal
      arch: amd64
      jdk: oraclejdk22
    - os: linux
      dist: focal
      arch: amd64
      jdk: openjdk22
    - os: linux
      dist: focal
      arch: arm64
      jdk: openjdk22
    - os: linux
      dist: focal
      arch: ppc64le
      jdk: openjdk22
    - os: linux
      dist: focal
      arch: s390x
      jdk: openjdk22
    - os: windows
      jdk: openjdk22
    - os: windows
      jdk: oraclejdk22
sudo: false
cache:
  directories:
  - $HOME/.m2
