/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_winapi_Fileapi */

#ifndef _Included_de_ibapl_jnhw_winapi_Fileapi
#define _Included_de_ibapl_jnhw_winapi_Fileapi
#ifdef __cplusplus
extern "C" {
#endif
#undef de_ibapl_jnhw_winapi_Fileapi_CREATE_ALWAYS
#define de_ibapl_jnhw_winapi_Fileapi_CREATE_ALWAYS 2L
#undef de_ibapl_jnhw_winapi_Fileapi_CREATE_NEW
#define de_ibapl_jnhw_winapi_Fileapi_CREATE_NEW 1L
#undef de_ibapl_jnhw_winapi_Fileapi_OPEN_ALWAYS
#define de_ibapl_jnhw_winapi_Fileapi_OPEN_ALWAYS 4L
#undef de_ibapl_jnhw_winapi_Fileapi_OPEN_EXISTING
#define de_ibapl_jnhw_winapi_Fileapi_OPEN_EXISTING 3L
#undef de_ibapl_jnhw_winapi_Fileapi_TRUNCATE_EXISTING
#define de_ibapl_jnhw_winapi_Fileapi_TRUNCATE_EXISTING 5L
/*
 * Class:     de_ibapl_jnhw_winapi_Fileapi
 * Method:    CreateFileW
 * Signature: (Ljava/lang/String;IIJIIJ)J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_winapi_Fileapi_CreateFileW
  (JNIEnv *, jclass, jstring, jint, jint, jlong, jint, jint, jlong);

/*
 * Class:     de_ibapl_jnhw_winapi_Fileapi
 * Method:    FlushFileBuffers
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_winapi_Fileapi_FlushFileBuffers
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_ibapl_jnhw_winapi_Fileapi
 * Method:    ReadFile
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_winapi_Fileapi_ReadFile__J_3BII
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     de_ibapl_jnhw_winapi_Fileapi
 * Method:    ReadFile
 * Signature: (JLjava/nio/ByteBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_winapi_Fileapi_ReadFile__JLjava_nio_ByteBuffer_2II
  (JNIEnv *, jclass, jlong, jobject, jint, jint);

/*
 * Class:     de_ibapl_jnhw_winapi_Fileapi
 * Method:    ReadFile
 * Signature: (JLjava/nio/ByteBuffer;IIJ)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_winapi_Fileapi_ReadFile__JLjava_nio_ByteBuffer_2IIJ
  (JNIEnv *, jclass, jlong, jobject, jint, jint, jlong);

/*
 * Class:     de_ibapl_jnhw_winapi_Fileapi
 * Method:    ReadFile
 * Signature: (JJII)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_winapi_Fileapi_ReadFile__JJII
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

/*
 * Class:     de_ibapl_jnhw_winapi_Fileapi
 * Method:    ReadFile
 * Signature: (JJIIJ)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_winapi_Fileapi_ReadFile__JJIIJ
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jlong);

/*
 * Class:     de_ibapl_jnhw_winapi_Fileapi
 * Method:    ReadFile
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_winapi_Fileapi_ReadFile__JJJI
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     de_ibapl_jnhw_winapi_Fileapi
 * Method:    ReadFile
 * Signature: (JJJIJ)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_winapi_Fileapi_ReadFile__JJJIJ
  (JNIEnv *, jclass, jlong, jlong, jlong, jint, jlong);

/*
 * Class:     de_ibapl_jnhw_winapi_Fileapi
 * Method:    ReadFileEx
 * Signature: (JLjava/nio/ByteBuffer;IIJJ)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_winapi_Fileapi_ReadFileEx__JLjava_nio_ByteBuffer_2IIJJ
  (JNIEnv *, jclass, jlong, jobject, jint, jint, jlong, jlong);

/*
 * Class:     de_ibapl_jnhw_winapi_Fileapi
 * Method:    ReadFileEx
 * Signature: (JJIIJJ)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_winapi_Fileapi_ReadFileEx__JJIIJJ
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jlong, jlong);

/*
 * Class:     de_ibapl_jnhw_winapi_Fileapi
 * Method:    ReadFileEx
 * Signature: (JJJIJJ)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_winapi_Fileapi_ReadFileEx__JJJIJJ
  (JNIEnv *, jclass, jlong, jlong, jlong, jint, jlong, jlong);

/*
 * Class:     de_ibapl_jnhw_winapi_Fileapi
 * Method:    WriteFile
 * Signature: (JB)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_winapi_Fileapi_WriteFile__JB
  (JNIEnv *, jclass, jlong, jbyte);

/*
 * Class:     de_ibapl_jnhw_winapi_Fileapi
 * Method:    WriteFile
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_winapi_Fileapi_WriteFile__J_3BII
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     de_ibapl_jnhw_winapi_Fileapi
 * Method:    WriteFile
 * Signature: (JLjava/nio/ByteBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_winapi_Fileapi_WriteFile__JLjava_nio_ByteBuffer_2II
  (JNIEnv *, jclass, jlong, jobject, jint, jint);

/*
 * Class:     de_ibapl_jnhw_winapi_Fileapi
 * Method:    WriteFile
 * Signature: (JLjava/nio/ByteBuffer;IIJ)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_winapi_Fileapi_WriteFile__JLjava_nio_ByteBuffer_2IIJ
  (JNIEnv *, jclass, jlong, jobject, jint, jint, jlong);

/*
 * Class:     de_ibapl_jnhw_winapi_Fileapi
 * Method:    WriteFile
 * Signature: (JJII)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_winapi_Fileapi_WriteFile__JJII
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

/*
 * Class:     de_ibapl_jnhw_winapi_Fileapi
 * Method:    WriteFile
 * Signature: (JJIIJ)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_winapi_Fileapi_WriteFile__JJIIJ
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jlong);

/*
 * Class:     de_ibapl_jnhw_winapi_Fileapi
 * Method:    WriteFile
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_winapi_Fileapi_WriteFile__JJJI
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     de_ibapl_jnhw_winapi_Fileapi
 * Method:    WriteFile
 * Signature: (JJJIJ)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_winapi_Fileapi_WriteFile__JJJIJ
  (JNIEnv *, jclass, jlong, jlong, jlong, jint, jlong);

/*
 * Class:     de_ibapl_jnhw_winapi_Fileapi
 * Method:    WriteFileEx
 * Signature: (JLjava/nio/ByteBuffer;IIJJ)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_winapi_Fileapi_WriteFileEx__JLjava_nio_ByteBuffer_2IIJJ
  (JNIEnv *, jclass, jlong, jobject, jint, jint, jlong, jlong);

/*
 * Class:     de_ibapl_jnhw_winapi_Fileapi
 * Method:    WriteFileEx
 * Signature: (JJIIJJ)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_winapi_Fileapi_WriteFileEx__JJIIJJ
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jlong, jlong);

/*
 * Class:     de_ibapl_jnhw_winapi_Fileapi
 * Method:    WriteFileEx
 * Signature: (JJJIJJ)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_winapi_Fileapi_WriteFileEx__JJJIJJ
  (JNIEnv *, jclass, jlong, jlong, jlong, jint, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
