/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_winapi_Errhandlingapi */

#ifndef _Included_de_ibapl_jnhw_winapi_Errhandlingapi
#define _Included_de_ibapl_jnhw_winapi_Errhandlingapi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_winapi_Errhandlingapi
 * Method:    initFields
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_winapi_Errhandlingapi_initFields
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_winapi_Errhandlingapi
 * Method:    GetLastError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_winapi_Errhandlingapi_GetLastError
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_winapi_Errhandlingapi
 * Method:    SetLastError
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_winapi_Errhandlingapi_SetLastError
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
