/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_winapi_Minwinbase_SECURITY_ATTRIBUTES */

#ifndef _Included_de_ibapl_jnhw_winapi_Minwinbase_SECURITY_ATTRIBUTES
#define _Included_de_ibapl_jnhw_winapi_Minwinbase_SECURITY_ATTRIBUTES
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_winapi_Minwinbase_SECURITY_ATTRIBUTES
 * Method:    sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_winapi_Minwinbase_00024SECURITY_1ATTRIBUTES_sizeof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_winapi_Minwinbase_SECURITY_ATTRIBUTES
 * Method:    nLength
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_winapi_Minwinbase_00024SECURITY_1ATTRIBUTES_nLength
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_winapi_Minwinbase_SECURITY_ATTRIBUTES
 * Method:    bInheritHandle
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_winapi_Minwinbase_00024SECURITY_1ATTRIBUTES_bInheritHandle
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
