/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_winapi_Winbase */

#ifndef _Included_de_ibapl_jnhw_winapi_Winbase
#define _Included_de_ibapl_jnhw_winapi_Winbase
#ifdef __cplusplus
extern "C" {
#endif
#undef de_ibapl_jnhw_winapi_Winbase_FILE_SKIP_COMPLETION_PORT_ON_SUCCESS
#define de_ibapl_jnhw_winapi_Winbase_FILE_SKIP_COMPLETION_PORT_ON_SUCCESS 1L
#undef de_ibapl_jnhw_winapi_Winbase_FILE_SKIP_SET_EVENT_ON_HANDLE
#define de_ibapl_jnhw_winapi_Winbase_FILE_SKIP_SET_EVENT_ON_HANDLE 2L
#undef de_ibapl_jnhw_winapi_Winbase_CE_RXOVER
#define de_ibapl_jnhw_winapi_Winbase_CE_RXOVER 1L
#undef de_ibapl_jnhw_winapi_Winbase_CE_OVERRUN
#define de_ibapl_jnhw_winapi_Winbase_CE_OVERRUN 2L
#undef de_ibapl_jnhw_winapi_Winbase_CE_RXPARITY
#define de_ibapl_jnhw_winapi_Winbase_CE_RXPARITY 4L
#undef de_ibapl_jnhw_winapi_Winbase_CE_FRAME
#define de_ibapl_jnhw_winapi_Winbase_CE_FRAME 8L
#undef de_ibapl_jnhw_winapi_Winbase_CE_BREAK
#define de_ibapl_jnhw_winapi_Winbase_CE_BREAK 16L
#undef de_ibapl_jnhw_winapi_Winbase_SETXOFF
#define de_ibapl_jnhw_winapi_Winbase_SETXOFF 1L
#undef de_ibapl_jnhw_winapi_Winbase_SETXON
#define de_ibapl_jnhw_winapi_Winbase_SETXON 2L
#undef de_ibapl_jnhw_winapi_Winbase_SETRTS
#define de_ibapl_jnhw_winapi_Winbase_SETRTS 3L
#undef de_ibapl_jnhw_winapi_Winbase_CLRRTS
#define de_ibapl_jnhw_winapi_Winbase_CLRRTS 4L
#undef de_ibapl_jnhw_winapi_Winbase_SETDTR
#define de_ibapl_jnhw_winapi_Winbase_SETDTR 5L
#undef de_ibapl_jnhw_winapi_Winbase_CLRDTR
#define de_ibapl_jnhw_winapi_Winbase_CLRDTR 6L
#undef de_ibapl_jnhw_winapi_Winbase_RESETDEV
#define de_ibapl_jnhw_winapi_Winbase_RESETDEV 7L
#undef de_ibapl_jnhw_winapi_Winbase_SETBREAK
#define de_ibapl_jnhw_winapi_Winbase_SETBREAK 8L
#undef de_ibapl_jnhw_winapi_Winbase_CLRBREAK
#define de_ibapl_jnhw_winapi_Winbase_CLRBREAK 9L
#undef de_ibapl_jnhw_winapi_Winbase_DTR_CONTROL_DISABLE
#define de_ibapl_jnhw_winapi_Winbase_DTR_CONTROL_DISABLE 0L
#undef de_ibapl_jnhw_winapi_Winbase_DTR_CONTROL_ENABLE
#define de_ibapl_jnhw_winapi_Winbase_DTR_CONTROL_ENABLE 1L
#undef de_ibapl_jnhw_winapi_Winbase_DTR_CONTROL_HANDSHAKE
#define de_ibapl_jnhw_winapi_Winbase_DTR_CONTROL_HANDSHAKE 2L
#undef de_ibapl_jnhw_winapi_Winbase_RTS_CONTROL_DISABLE
#define de_ibapl_jnhw_winapi_Winbase_RTS_CONTROL_DISABLE 0L
#undef de_ibapl_jnhw_winapi_Winbase_RTS_CONTROL_ENABLE
#define de_ibapl_jnhw_winapi_Winbase_RTS_CONTROL_ENABLE 1L
#undef de_ibapl_jnhw_winapi_Winbase_RTS_CONTROL_HANDSHAKE
#define de_ibapl_jnhw_winapi_Winbase_RTS_CONTROL_HANDSHAKE 3L
#undef de_ibapl_jnhw_winapi_Winbase_RTS_CONTROL_TOGGLE
#define de_ibapl_jnhw_winapi_Winbase_RTS_CONTROL_TOGGLE 4L
#undef de_ibapl_jnhw_winapi_Winbase_NOPARITY
#define de_ibapl_jnhw_winapi_Winbase_NOPARITY 0L
#undef de_ibapl_jnhw_winapi_Winbase_ODDPARITY
#define de_ibapl_jnhw_winapi_Winbase_ODDPARITY 1L
#undef de_ibapl_jnhw_winapi_Winbase_EVENPARITY
#define de_ibapl_jnhw_winapi_Winbase_EVENPARITY 2L
#undef de_ibapl_jnhw_winapi_Winbase_MARKPARITY
#define de_ibapl_jnhw_winapi_Winbase_MARKPARITY 3L
#undef de_ibapl_jnhw_winapi_Winbase_SPACEPARITY
#define de_ibapl_jnhw_winapi_Winbase_SPACEPARITY 4L
#undef de_ibapl_jnhw_winapi_Winbase_ONESTOPBIT
#define de_ibapl_jnhw_winapi_Winbase_ONESTOPBIT 0L
#undef de_ibapl_jnhw_winapi_Winbase_ONE5STOPBITS
#define de_ibapl_jnhw_winapi_Winbase_ONE5STOPBITS 1L
#undef de_ibapl_jnhw_winapi_Winbase_TWOSTOPBITS
#define de_ibapl_jnhw_winapi_Winbase_TWOSTOPBITS 2L
#undef de_ibapl_jnhw_winapi_Winbase_MS_CTS_ON
#define de_ibapl_jnhw_winapi_Winbase_MS_CTS_ON 16L
#undef de_ibapl_jnhw_winapi_Winbase_MS_DSR_ON
#define de_ibapl_jnhw_winapi_Winbase_MS_DSR_ON 32L
#undef de_ibapl_jnhw_winapi_Winbase_MS_RING_ON
#define de_ibapl_jnhw_winapi_Winbase_MS_RING_ON 64L
#undef de_ibapl_jnhw_winapi_Winbase_MS_RLSD_ON
#define de_ibapl_jnhw_winapi_Winbase_MS_RLSD_ON 128L
#undef de_ibapl_jnhw_winapi_Winbase_INFINITE
#define de_ibapl_jnhw_winapi_Winbase_INFINITE -1L
#undef de_ibapl_jnhw_winapi_Winbase_STD_INPUT_HANDLE
#define de_ibapl_jnhw_winapi_Winbase_STD_INPUT_HANDLE -10L
#undef de_ibapl_jnhw_winapi_Winbase_STD_OUTPUT_HANDLE
#define de_ibapl_jnhw_winapi_Winbase_STD_OUTPUT_HANDLE -11L
#undef de_ibapl_jnhw_winapi_Winbase_STD_ERROR_HANDLE
#define de_ibapl_jnhw_winapi_Winbase_STD_ERROR_HANDLE -12L
#undef de_ibapl_jnhw_winapi_Winbase_WAIT_FAILED
#define de_ibapl_jnhw_winapi_Winbase_WAIT_FAILED -1L
#undef de_ibapl_jnhw_winapi_Winbase_WAIT_OBJECT_0
#define de_ibapl_jnhw_winapi_Winbase_WAIT_OBJECT_0 0L
#undef de_ibapl_jnhw_winapi_Winbase_WAIT_ABANDONED
#define de_ibapl_jnhw_winapi_Winbase_WAIT_ABANDONED 128L
#undef de_ibapl_jnhw_winapi_Winbase_WAIT_IO_COMPLETION
#define de_ibapl_jnhw_winapi_Winbase_WAIT_IO_COMPLETION 192L
#undef de_ibapl_jnhw_winapi_Winbase_FILE_FLAG_WRITE_THROUGH
#define de_ibapl_jnhw_winapi_Winbase_FILE_FLAG_WRITE_THROUGH -2147483648L
#undef de_ibapl_jnhw_winapi_Winbase_FILE_FLAG_OVERLAPPED
#define de_ibapl_jnhw_winapi_Winbase_FILE_FLAG_OVERLAPPED 1073741824L
#undef de_ibapl_jnhw_winapi_Winbase_FILE_FLAG_NO_BUFFERING
#define de_ibapl_jnhw_winapi_Winbase_FILE_FLAG_NO_BUFFERING 536870912L
#undef de_ibapl_jnhw_winapi_Winbase_FILE_FLAG_RANDOM_ACCESS
#define de_ibapl_jnhw_winapi_Winbase_FILE_FLAG_RANDOM_ACCESS 268435456L
#undef de_ibapl_jnhw_winapi_Winbase_FILE_FLAG_SEQUENTIAL_SCAN
#define de_ibapl_jnhw_winapi_Winbase_FILE_FLAG_SEQUENTIAL_SCAN 134217728L
#undef de_ibapl_jnhw_winapi_Winbase_FILE_FLAG_DELETE_ON_CLOSE
#define de_ibapl_jnhw_winapi_Winbase_FILE_FLAG_DELETE_ON_CLOSE 67108864L
#undef de_ibapl_jnhw_winapi_Winbase_FILE_FLAG_BACKUP_SEMANTICS
#define de_ibapl_jnhw_winapi_Winbase_FILE_FLAG_BACKUP_SEMANTICS 33554432L
#undef de_ibapl_jnhw_winapi_Winbase_FILE_FLAG_POSIX_SEMANTICS
#define de_ibapl_jnhw_winapi_Winbase_FILE_FLAG_POSIX_SEMANTICS 16777216L
#undef de_ibapl_jnhw_winapi_Winbase_FILE_FLAG_SESSION_AWARE
#define de_ibapl_jnhw_winapi_Winbase_FILE_FLAG_SESSION_AWARE 8388608L
#undef de_ibapl_jnhw_winapi_Winbase_FILE_FLAG_OPEN_REPARSE_POINT
#define de_ibapl_jnhw_winapi_Winbase_FILE_FLAG_OPEN_REPARSE_POINT 2097152L
#undef de_ibapl_jnhw_winapi_Winbase_FILE_FLAG_OPEN_NO_RECALL
#define de_ibapl_jnhw_winapi_Winbase_FILE_FLAG_OPEN_NO_RECALL 1048576L
#undef de_ibapl_jnhw_winapi_Winbase_SECURITY_ANONYMOUS
#define de_ibapl_jnhw_winapi_Winbase_SECURITY_ANONYMOUS 0L
#undef de_ibapl_jnhw_winapi_Winbase_SECURITY_IDENTIFICATION
#define de_ibapl_jnhw_winapi_Winbase_SECURITY_IDENTIFICATION 65536L
#undef de_ibapl_jnhw_winapi_Winbase_SECURITY_IMPERSONATION
#define de_ibapl_jnhw_winapi_Winbase_SECURITY_IMPERSONATION 131072L
#undef de_ibapl_jnhw_winapi_Winbase_SECURITY_DELEGATION
#define de_ibapl_jnhw_winapi_Winbase_SECURITY_DELEGATION 196608L
#undef de_ibapl_jnhw_winapi_Winbase_SECURITY_CONTEXT_TRACKING
#define de_ibapl_jnhw_winapi_Winbase_SECURITY_CONTEXT_TRACKING 262144L
#undef de_ibapl_jnhw_winapi_Winbase_SECURITY_EFFECTIVE_ONLY
#define de_ibapl_jnhw_winapi_Winbase_SECURITY_EFFECTIVE_ONLY 524288L
/*
 * Class:     de_ibapl_jnhw_winapi_Winbase
 * Method:    ClearCommBreak
 * Signature: (Lde/ibapl/jnhw/winapi/Winnt/HANDLE;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_winapi_Winbase_ClearCommBreak
  (JNIEnv *, jclass, jobject);

/*
 * Class:     de_ibapl_jnhw_winapi_Winbase
 * Method:    ClearCommError
 * Signature: (Lde/ibapl/jnhw/winapi/Winnt/HANDLE;Lde/ibapl/jnhw/common/references/IntRef;Lde/ibapl/jnhw/winapi/Winbase/COMSTAT;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_winapi_Winbase_ClearCommError
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     de_ibapl_jnhw_winapi_Winbase
 * Method:    EscapeCommFunction
 * Signature: (Lde/ibapl/jnhw/winapi/Winnt/HANDLE;I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_winapi_Winbase_EscapeCommFunction
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     de_ibapl_jnhw_winapi_Winbase
 * Method:    GetCommModemStatus
 * Signature: (Lde/ibapl/jnhw/winapi/Winnt/HANDLE;Lde/ibapl/jnhw/common/references/IntRef;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_winapi_Winbase_GetCommModemStatus
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     de_ibapl_jnhw_winapi_Winbase
 * Method:    GetCommState
 * Signature: (Lde/ibapl/jnhw/winapi/Winnt/HANDLE;Lde/ibapl/jnhw/winapi/Winbase/DCB;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_winapi_Winbase_GetCommState
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     de_ibapl_jnhw_winapi_Winbase
 * Method:    GetCommTimeouts
 * Signature: (Lde/ibapl/jnhw/winapi/Winnt/HANDLE;Lde/ibapl/jnhw/winapi/Winbase/COMMTIMEOUTS;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_winapi_Winbase_GetCommTimeouts
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     de_ibapl_jnhw_winapi_Winbase
 * Method:    SetCommBreak
 * Signature: (Lde/ibapl/jnhw/winapi/Winnt/HANDLE;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_winapi_Winbase_SetCommBreak
  (JNIEnv *, jclass, jobject);

/*
 * Class:     de_ibapl_jnhw_winapi_Winbase
 * Method:    SetCommState
 * Signature: (Lde/ibapl/jnhw/winapi/Winnt/HANDLE;Lde/ibapl/jnhw/winapi/Winbase/DCB;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_winapi_Winbase_SetCommState
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     de_ibapl_jnhw_winapi_Winbase
 * Method:    SetCommTimeouts
 * Signature: (Lde/ibapl/jnhw/winapi/Winnt/HANDLE;Lde/ibapl/jnhw/winapi/Winbase/COMMTIMEOUTS;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_winapi_Winbase_SetCommTimeouts
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     de_ibapl_jnhw_winapi_Winbase
 * Method:    SetFileCompletionNotificationModes
 * Signature: (Lde/ibapl/jnhw/winapi/Winnt/HANDLE;B)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_winapi_Winbase_SetFileCompletionNotificationModes
  (JNIEnv *, jclass, jobject, jbyte);

/*
 * Class:     de_ibapl_jnhw_winapi_Winbase
 * Method:    BindIoCompletionCallback
 * Signature: (Lde/ibapl/jnhw/winapi/Winnt/HANDLE;Lde/ibapl/jnhw/winapi/Minwinbase/LPOVERLAPPED_COMPLETION_ROUTINE;I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_winapi_Winbase_BindIoCompletionCallback
  (JNIEnv *, jclass, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
