/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_winapi_Synchapi */

#ifndef _Included_de_ibapl_jnhw_winapi_Synchapi
#define _Included_de_ibapl_jnhw_winapi_Synchapi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_winapi_Synchapi
 * Method:    initFields
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_winapi_Synchapi_initFields
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_winapi_Synchapi
 * Method:    CreateEventW
 * Signature: (Lde/ibapl/jnhw/winapi/Minwinbase/SECURITY_ATTRIBUTES;ZZLjava/lang/String;)Lde/ibapl/jnhw/winapi/Winnt/HANDLE;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_winapi_Synchapi_CreateEventW
  (JNIEnv *, jclass, jobject, jboolean, jboolean, jstring);

/*
 * Class:     de_ibapl_jnhw_winapi_Synchapi
 * Method:    ResetEvent
 * Signature: (Lde/ibapl/jnhw/winapi/Winnt/HANDLE;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_winapi_Synchapi_ResetEvent
  (JNIEnv *, jclass, jobject);

/*
 * Class:     de_ibapl_jnhw_winapi_Synchapi
 * Method:    SetEvent
 * Signature: (Lde/ibapl/jnhw/winapi/Winnt/HANDLE;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_winapi_Synchapi_SetEvent
  (JNIEnv *, jclass, jobject);

/*
 * Class:     de_ibapl_jnhw_winapi_Synchapi
 * Method:    WaitForSingleObject
 * Signature: (Lde/ibapl/jnhw/winapi/Winnt/HANDLE;J)J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_winapi_Synchapi_WaitForSingleObject
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     de_ibapl_jnhw_winapi_Synchapi
 * Method:    WaitForSingleObjectEx
 * Signature: (Lde/ibapl/jnhw/winapi/Winnt/HANDLE;JZ)J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_winapi_Synchapi_WaitForSingleObjectEx
  (JNIEnv *, jclass, jobject, jlong, jboolean);

/*
 * Class:     de_ibapl_jnhw_winapi_Synchapi
 * Method:    SleepEx
 * Signature: (JZ)J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_winapi_Synchapi_SleepEx
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     de_ibapl_jnhw_winapi_Synchapi
 * Method:    WaitForMultipleObjects_ArgsOK
 * Signature: (ILde/ibapl/jnhw/winapi/Winnt/ArrayOfHandle;ZJ)J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_winapi_Synchapi_WaitForMultipleObjects_1ArgsOK
  (JNIEnv *, jclass, jint, jobject, jboolean, jlong);

/*
 * Class:     de_ibapl_jnhw_winapi_Synchapi
 * Method:    WaitForMultipleObjectsEx_ArgsOK
 * Signature: (ILde/ibapl/jnhw/winapi/Winnt/ArrayOfHandle;ZJZ)J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_winapi_Synchapi_WaitForMultipleObjectsEx_1ArgsOK
  (JNIEnv *, jclass, jint, jobject, jboolean, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
