/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_winapi_Ioapiset */

#ifndef _Included_de_ibapl_jnhw_winapi_Ioapiset
#define _Included_de_ibapl_jnhw_winapi_Ioapiset
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_winapi_Ioapiset
 * Method:    initFields
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_winapi_Ioapiset_initFields
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_winapi_Ioapiset
 * Method:    CancelIo
 * Signature: (Lde/ibapl/jnhw/winapi/Winnt/HANDLE;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_winapi_Ioapiset_CancelIo
  (JNIEnv *, jclass, jobject);

/*
 * Class:     de_ibapl_jnhw_winapi_Ioapiset
 * Method:    CancelIoEx
 * Signature: (Lde/ibapl/jnhw/winapi/Winnt/HANDLE;Lde/ibapl/jnhw/winapi/Minwinbase/OVERLAPPED;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_winapi_Ioapiset_CancelIoEx
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     de_ibapl_jnhw_winapi_Ioapiset
 * Method:    GetOverlappedResult
 * Signature: (Lde/ibapl/jnhw/winapi/Winnt/HANDLE;Lde/ibapl/jnhw/winapi/Minwinbase/OVERLAPPED;Z)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_winapi_Ioapiset_GetOverlappedResult
  (JNIEnv *, jclass, jobject, jobject, jboolean);

/*
 * Class:     de_ibapl_jnhw_winapi_Ioapiset
 * Method:    DeviceIoControl
 * Signature: (Lde/ibapl/jnhw/winapi/Winnt/HANDLE;ILde/ibapl/jnhw/common/memory/OpaqueMemory32;IILde/ibapl/jnhw/common/memory/OpaqueMemory32;IILde/ibapl/jnhw/winapi/Minwinbase/OVERLAPPED;)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_winapi_Ioapiset_DeviceIoControl__Lde_ibapl_jnhw_winapi_Winnt_HANDLE_2ILde_ibapl_jnhw_common_memory_OpaqueMemory32_2IILde_ibapl_jnhw_common_memory_OpaqueMemory32_2IILde_ibapl_jnhw_winapi_Minwinbase_OVERLAPPED_2
  (JNIEnv *, jobject, jobject, jint, jobject, jint, jint, jobject, jint, jint, jobject);

/*
 * Class:     de_ibapl_jnhw_winapi_Ioapiset
 * Method:    DeviceIoControl
 * Signature: (Lde/ibapl/jnhw/winapi/Winnt/HANDLE;ILjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Lde/ibapl/jnhw/winapi/Minwinbase/OVERLAPPED;)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_winapi_Ioapiset_DeviceIoControl__Lde_ibapl_jnhw_winapi_Winnt_HANDLE_2ILjava_nio_ByteBuffer_2Ljava_nio_ByteBuffer_2Lde_ibapl_jnhw_winapi_Minwinbase_OVERLAPPED_2
  (JNIEnv *, jobject, jobject, jint, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
