/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_winapi_Handleapi */

#ifndef _Included_de_ibapl_jnhw_winapi_Handleapi
#define _Included_de_ibapl_jnhw_winapi_Handleapi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_winapi_Handleapi
 * Method:    CloseHandle
 * Signature: (Lde/ibapl/jnhw/winapi/Winnt/HANDLE;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_winapi_Handleapi_CloseHandle
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
