/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_winapi_Winbase_COMSTAT */

#ifndef _Included_de_ibapl_jnhw_winapi_Winbase_COMSTAT
#define _Included_de_ibapl_jnhw_winapi_Winbase_COMSTAT
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_winapi_Winbase_COMSTAT
 * Method:    sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_winapi_Winbase_00024COMSTAT_sizeof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_winapi_Winbase_COMSTAT
 * Method:    fCtsHold
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_winapi_Winbase_00024COMSTAT_fCtsHold
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_winapi_Winbase_COMSTAT
 * Method:    fDsrHold
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_winapi_Winbase_00024COMSTAT_fDsrHold
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_winapi_Winbase_COMSTAT
 * Method:    fRlsdHold
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_winapi_Winbase_00024COMSTAT_fRlsdHold
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_winapi_Winbase_COMSTAT
 * Method:    fXoffHold
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_winapi_Winbase_00024COMSTAT_fXoffHold
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_winapi_Winbase_COMSTAT
 * Method:    fXoffSent
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_winapi_Winbase_00024COMSTAT_fXoffSent
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_winapi_Winbase_COMSTAT
 * Method:    fEof
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_winapi_Winbase_00024COMSTAT_fEof
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_winapi_Winbase_COMSTAT
 * Method:    fTxim
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_winapi_Winbase_00024COMSTAT_fTxim
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_winapi_Winbase_COMSTAT
 * Method:    fReserved
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_winapi_Winbase_00024COMSTAT_fReserved
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_winapi_Winbase_COMSTAT
 * Method:    cbInQue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_winapi_Winbase_00024COMSTAT_cbInQue
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_winapi_Winbase_COMSTAT
 * Method:    cbOutQue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_winapi_Winbase_00024COMSTAT_cbOutQue
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
