/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_winapi_Minwinbase */

#ifndef _Included_de_ibapl_jnhw_winapi_Minwinbase
#define _Included_de_ibapl_jnhw_winapi_Minwinbase
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_winapi_Minwinbase
 * Method:    initFields
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_winapi_Minwinbase_initFields
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
