/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_winapi_Ioapiset */

#ifndef _Included_de_ibapl_jnhw_winapi_Ioapiset
#define _Included_de_ibapl_jnhw_winapi_Ioapiset
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_winapi_Ioapiset
 * Method:    CancelIo
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_winapi_Ioapiset_CancelIo
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_ibapl_jnhw_winapi_Ioapiset
 * Method:    CancelIoEx
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_winapi_Ioapiset_CancelIoEx
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     de_ibapl_jnhw_winapi_Ioapiset
 * Method:    DeviceIoControl
 * Signature: (JIJIJIJ)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_winapi_Ioapiset_DeviceIoControl
  (JNIEnv *, jclass, jlong, jint, jlong, jint, jlong, jint, jlong);

/*
 * Class:     de_ibapl_jnhw_winapi_Ioapiset
 * Method:    GetOverlappedResult
 * Signature: (JJZ)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_winapi_Ioapiset_GetOverlappedResult
  (JNIEnv *, jclass, jlong, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
