/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_winapi_ProcessEnv */

#ifndef _Included_de_ibapl_jnhw_winapi_ProcessEnv
#define _Included_de_ibapl_jnhw_winapi_ProcessEnv
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_winapi_ProcessEnv
 * Method:    GetStdHandle0
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_winapi_ProcessEnv_GetStdHandle0
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
