/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_winapi_Minwinbase_OVERLAPPED */

#ifndef _Included_de_ibapl_jnhw_winapi_Minwinbase_OVERLAPPED
#define _Included_de_ibapl_jnhw_winapi_Minwinbase_OVERLAPPED
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_winapi_Minwinbase_OVERLAPPED
 * Method:    native2Layout
 * Signature: (Ljava/lang/Class;)Lde/ibapl/jnhw/winapi/Minwinbase/OVERLAPPED/Layout;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_winapi_Minwinbase_00024OVERLAPPED_native2Layout
  (JNIEnv *, jclass, jclass);

#ifdef __cplusplus
}
#endif
#endif
