/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_winapi_Winnt_LPWSTR */

#ifndef _Included_de_ibapl_jnhw_winapi_Winnt_LPWSTR
#define _Included_de_ibapl_jnhw_winapi_Winnt_LPWSTR
#ifdef __cplusplus
extern "C" {
#endif
#undef de_ibapl_jnhw_winapi_Winnt_LPWSTR_SIZE_OF_WCHAR
#define de_ibapl_jnhw_winapi_Winnt_LPWSTR_SIZE_OF_WCHAR 2L
/*
 * Class:     de_ibapl_jnhw_winapi_Winnt_LPWSTR
 * Method:    sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_winapi_Winnt_00024LPWSTR_sizeof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_winapi_Winnt_LPWSTR
 * Method:    getString
 * Signature: (Lde/ibapl/jnhw/common/memory/OpaqueMemory32;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_ibapl_jnhw_winapi_Winnt_00024LPWSTR_getString
  (JNIEnv *, jclass, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
