/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_winapi_Processthreadsapi */

#ifndef _Included_de_ibapl_jnhw_winapi_Processthreadsapi
#define _Included_de_ibapl_jnhw_winapi_Processthreadsapi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_winapi_Processthreadsapi
 * Method:    QueueUserAPC
 * Signature: (Lde/ibapl/jnhw/winapi/Winnt/PAPCFUNC;Lde/ibapl/jnhw/winapi/Winnt/HANDLE;J)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_winapi_Processthreadsapi_QueueUserAPC
  (JNIEnv *, jclass, jobject, jobject, jlong);

/*
 * Class:     de_ibapl_jnhw_winapi_Processthreadsapi
 * Method:    GetCurrentThread
 * Signature: ()Lde/ibapl/jnhw/winapi/Winnt/HANDLE;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_winapi_Processthreadsapi_GetCurrentThread
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
