/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_winapi_Processthreadsapi */

#ifndef _Included_de_ibapl_jnhw_winapi_Processthreadsapi
#define _Included_de_ibapl_jnhw_winapi_Processthreadsapi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_winapi_Processthreadsapi
 * Method:    QueueUserAPC
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_winapi_Processthreadsapi_QueueUserAPC
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     de_ibapl_jnhw_winapi_Processthreadsapi
 * Method:    GetCurrentThread0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_winapi_Processthreadsapi_GetCurrentThread0
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
