/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_winapi_Synchapi */

#ifndef _Included_de_ibapl_jnhw_winapi_Synchapi
#define _Included_de_ibapl_jnhw_winapi_Synchapi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_winapi_Synchapi
 * Method:    CreateEventW
 * Signature: (JZZLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_winapi_Synchapi_CreateEventW
  (JNIEnv *, jclass, jlong, jboolean, jboolean, jstring);

/*
 * Class:     de_ibapl_jnhw_winapi_Synchapi
 * Method:    ResetEvent
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_winapi_Synchapi_ResetEvent
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_ibapl_jnhw_winapi_Synchapi
 * Method:    SetEvent
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_winapi_Synchapi_SetEvent
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_ibapl_jnhw_winapi_Synchapi
 * Method:    SleepEx0
 * Signature: (JZ)J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_winapi_Synchapi_SleepEx0
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     de_ibapl_jnhw_winapi_Synchapi
 * Method:    WaitForMultipleObjects
 * Signature: (IJZJ)J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_winapi_Synchapi_WaitForMultipleObjects
  (JNIEnv *, jclass, jint, jlong, jboolean, jlong);

/*
 * Class:     de_ibapl_jnhw_winapi_Synchapi
 * Method:    WaitForMultipleObjectsEx
 * Signature: (IJZJZ)J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_winapi_Synchapi_WaitForMultipleObjectsEx
  (JNIEnv *, jclass, jint, jlong, jboolean, jlong, jboolean);

/*
 * Class:     de_ibapl_jnhw_winapi_Synchapi
 * Method:    WaitForSingleObject
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_winapi_Synchapi_WaitForSingleObject
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     de_ibapl_jnhw_winapi_Synchapi
 * Method:    WaitForSingleObjectEx
 * Signature: (JJZ)J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_winapi_Synchapi_WaitForSingleObjectEx
  (JNIEnv *, jclass, jlong, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
