/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_winapi_Minwinbase_SECURITY_ATTRIBUTES */

#ifndef _Included_de_ibapl_jnhw_winapi_Minwinbase_SECURITY_ATTRIBUTES
#define _Included_de_ibapl_jnhw_winapi_Minwinbase_SECURITY_ATTRIBUTES
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_winapi_Minwinbase_SECURITY_ATTRIBUTES
 * Method:    native2Layout
 * Signature: (Ljava/lang/Class;)Lde/ibapl/jnhw/winapi/Minwinbase/SECURITY_ATTRIBUTES/Layout;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_winapi_Minwinbase_00024SECURITY_1ATTRIBUTES_native2Layout
  (JNIEnv *, jclass, jclass);

#ifdef __cplusplus
}
#endif
#endif
