/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_downcall_jni_JniMi__D___I__I */

#ifndef _Included_de_ibapl_jnhw_common_downcall_jni_JniMi__D___I__I
#define _Included_de_ibapl_jnhw_common_downcall_jni_JniMi__D___I__I
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_common_downcall_jni_JniMi__D___I__I
 * Method:    invoke__D___I__I
 * Signature: (JII)D
 */
JNIEXPORT jdouble JNICALL Java_de_ibapl_jnhw_common_downcall_jni_JniMi_1_1D_1_1_1I_1_1I_invoke_1_1D_1_1_1I_1_1I
  (JNIEnv *, jclass, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
