/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_memory_OpaqueMemory64 */

#ifndef _Included_de_ibapl_jnhw_common_memory_OpaqueMemory64
#define _Included_de_ibapl_jnhw_common_memory_OpaqueMemory64
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_common_memory_OpaqueMemory64
 * Method:    copy
 * Signature: ([BILde/ibapl/jnhw/common/memory/OpaqueMemory64;JI)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_common_memory_OpaqueMemory64_copy___3BILde_ibapl_jnhw_common_memory_OpaqueMemory64_2JI
  (JNIEnv *, jclass, jbyteArray, jint, jobject, jlong, jint);

/*
 * Class:     de_ibapl_jnhw_common_memory_OpaqueMemory64
 * Method:    copy
 * Signature: (Lde/ibapl/jnhw/common/memory/OpaqueMemory64;J[BII)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_common_memory_OpaqueMemory64_copy__Lde_ibapl_jnhw_common_memory_OpaqueMemory64_2J_3BII
  (JNIEnv *, jclass, jobject, jlong, jbyteArray, jint, jint);

/*
 * Class:     de_ibapl_jnhw_common_memory_OpaqueMemory64
 * Method:    memset
 * Signature: (Lde/ibapl/jnhw/common/memory/OpaqueMemory64;B)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_common_memory_OpaqueMemory64_memset
  (JNIEnv *, jclass, jobject, jbyte);

/*
 * Class:     de_ibapl_jnhw_common_memory_OpaqueMemory64
 * Method:    getByte
 * Signature: (Lde/ibapl/jnhw/common/memory/OpaqueMemory64;J)B
 */
JNIEXPORT jbyte JNICALL Java_de_ibapl_jnhw_common_memory_OpaqueMemory64_getByte
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     de_ibapl_jnhw_common_memory_OpaqueMemory64
 * Method:    setByte
 * Signature: (Lde/ibapl/jnhw/common/memory/OpaqueMemory64;JB)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_common_memory_OpaqueMemory64_setByte
  (JNIEnv *, jclass, jobject, jlong, jbyte);

#ifdef __cplusplus
}
#endif
#endif
