/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_nativecall_CallNative_IJ_V */

#ifndef _Included_de_ibapl_jnhw_common_nativecall_CallNative_IJ_V
#define _Included_de_ibapl_jnhw_common_nativecall_CallNative_IJ_V
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_common_nativecall_CallNative_IJ_V
 * Method:    call
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_common_nativecall_CallNative_1IJ_1V_call
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
