/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_memory_UnsafeMemoryAccessor */

#ifndef _Included_de_ibapl_jnhw_common_memory_UnsafeMemoryAccessor
#define _Included_de_ibapl_jnhw_common_memory_UnsafeMemoryAccessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_common_memory_UnsafeMemoryAccessor
 * Method:    uintptr_t0
 * Signature: (JLjava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_common_memory_UnsafeMemoryAccessor_uintptr_1t0
  (JNIEnv *, jclass, jlong, jobject, jint);

/*
 * Class:     de_ibapl_jnhw_common_memory_UnsafeMemoryAccessor
 * Method:    getStringUTF0
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_ibapl_jnhw_common_memory_UnsafeMemoryAccessor_getStringUTF0
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
