/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_memory_Uint32_t */

#ifndef _Included_de_ibapl_jnhw_common_memory_Uint32_t
#define _Included_de_ibapl_jnhw_common_memory_Uint32_t
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_common_memory_Uint32_t
 * Method:    sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_common_memory_Uint32_1t_sizeof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_common_memory_Uint32_t
 * Method:    alignof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_common_memory_Uint32_1t_alignof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_common_memory_Uint32_t
 * Method:    rawUint32_t
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_common_memory_Uint32_1t_rawUint32_1t__
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_common_memory_Uint32_t
 * Method:    rawUint32_t
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_common_memory_Uint32_1t_rawUint32_1t__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_ibapl_jnhw_common_memory_Uint32_t
 * Method:    nativeToString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_ibapl_jnhw_common_memory_Uint32_1t_nativeToString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
