/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_downcall_jni_JniMi__I___I__L__A */

#ifndef _Included_de_ibapl_jnhw_common_downcall_jni_JniMi__I___I__L__A
#define _Included_de_ibapl_jnhw_common_downcall_jni_JniMi__I___I__L__A
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_common_downcall_jni_JniMi__I___I__L__A
 * Method:    invoke__I___I__L__A
 * Signature: (JIJJ)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_common_downcall_jni_JniMi_1_1I_1_1_1I_1_1L_1_1A_invoke_1_1I_1_1_1I_1_1L_1_1A
  (JNIEnv *, jclass, jlong, jint, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
