/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_memory_AbstractNativeMemory */

#ifndef _Included_de_ibapl_jnhw_common_memory_AbstractNativeMemory
#define _Included_de_ibapl_jnhw_common_memory_AbstractNativeMemory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_common_memory_AbstractNativeMemory
 * Method:    ENOMEM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_common_memory_AbstractNativeMemory_ENOMEM
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_common_memory_AbstractNativeMemory
 * Method:    malloc
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_common_memory_AbstractNativeMemory_malloc__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_ibapl_jnhw_common_memory_AbstractNativeMemory
 * Method:    malloc
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_common_memory_AbstractNativeMemory_malloc__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_ibapl_jnhw_common_memory_AbstractNativeMemory
 * Method:    calloc
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_common_memory_AbstractNativeMemory_calloc__II
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     de_ibapl_jnhw_common_memory_AbstractNativeMemory
 * Method:    calloc
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_common_memory_AbstractNativeMemory_calloc__JJ
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
