/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_memory_OpaqueMemory32 */

#ifndef _Included_de_ibapl_jnhw_common_memory_OpaqueMemory32
#define _Included_de_ibapl_jnhw_common_memory_OpaqueMemory32
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_common_memory_OpaqueMemory32
 * Method:    copy
 * Signature: ([BILde/ibapl/jnhw/common/memory/OpaqueMemory32;II)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_common_memory_OpaqueMemory32_copy___3BILde_ibapl_jnhw_common_memory_OpaqueMemory32_2II
  (JNIEnv *, jclass, jbyteArray, jint, jobject, jint, jint);

/*
 * Class:     de_ibapl_jnhw_common_memory_OpaqueMemory32
 * Method:    copy
 * Signature: (Lde/ibapl/jnhw/common/memory/OpaqueMemory32;I[BII)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_common_memory_OpaqueMemory32_copy__Lde_ibapl_jnhw_common_memory_OpaqueMemory32_2I_3BII
  (JNIEnv *, jclass, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     de_ibapl_jnhw_common_memory_OpaqueMemory32
 * Method:    memset
 * Signature: (Lde/ibapl/jnhw/common/memory/OpaqueMemory32;B)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_common_memory_OpaqueMemory32_memset
  (JNIEnv *, jclass, jobject, jbyte);

/*
 * Class:     de_ibapl_jnhw_common_memory_OpaqueMemory32
 * Method:    getByte
 * Signature: (Lde/ibapl/jnhw/common/memory/OpaqueMemory32;I)B
 */
JNIEXPORT jbyte JNICALL Java_de_ibapl_jnhw_common_memory_OpaqueMemory32_getByte
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     de_ibapl_jnhw_common_memory_OpaqueMemory32
 * Method:    setByte
 * Signature: (Lde/ibapl/jnhw/common/memory/OpaqueMemory32;IB)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_common_memory_OpaqueMemory32_setByte
  (JNIEnv *, jclass, jobject, jint, jbyte);

#ifdef __cplusplus
}
#endif
#endif
