/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_callback_Callback_NativeRunnable */

#ifndef _Included_de_ibapl_jnhw_common_callback_Callback_NativeRunnable
#define _Included_de_ibapl_jnhw_common_callback_Callback_NativeRunnable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_common_callback_Callback_NativeRunnable
 * Method:    initNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_common_callback_Callback_1NativeRunnable_initNative
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_common_callback_Callback_NativeRunnable
 * Method:    aquire0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_common_callback_Callback_1NativeRunnable_aquire0
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
