/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_LibJnhwCommonLoader */

#ifndef _Included_de_ibapl_jnhw_common_LibJnhwCommonLoader
#define _Included_de_ibapl_jnhw_common_LibJnhwCommonLoader
#ifdef __cplusplus
extern "C" {
#endif
#undef de_ibapl_jnhw_common_LibJnhwCommonLoader_LIB_JNHW_COMMON_VERSION
#define de_ibapl_jnhw_common_LibJnhwCommonLoader_LIB_JNHW_COMMON_VERSION 3L
/*
 * Class:     de_ibapl_jnhw_common_LibJnhwCommonLoader
 * Method:    initNativeClasses
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_common_LibJnhwCommonLoader_initNativeClasses
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
