/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_downcall_jni_JniMi__V___B__I */

#ifndef _Included_de_ibapl_jnhw_common_downcall_jni_JniMi__V___B__I
#define _Included_de_ibapl_jnhw_common_downcall_jni_JniMi__V___B__I
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_common_downcall_jni_JniMi__V___B__I
 * Method:    invoke__V___B__I
 * Signature: (JBI)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_common_downcall_jni_JniMi_1_1V_1_1_1B_1_1I_invoke_1_1V_1_1_1B_1_1I
  (JNIEnv *, jclass, jlong, jbyte, jint);

#ifdef __cplusplus
}
#endif
#endif
