/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_downcall_jni_JniMi__L___I__A__L */

#ifndef _Included_de_ibapl_jnhw_common_downcall_jni_JniMi__L___I__A__L
#define _Included_de_ibapl_jnhw_common_downcall_jni_JniMi__L___I__A__L
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_common_downcall_jni_JniMi__L___I__A__L
 * Method:    invoke__L___I__A__L
 * Signature: (JIJJ)J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_common_downcall_jni_JniMi_1_1L_1_1_1I_1_1A_1_1L_invoke_1_1L_1_1_1I_1_1A_1_1L
  (JNIEnv *, jclass, jlong, jint, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
