/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_downcall_jni_JniMi__V___B__L */

#ifndef _Included_de_ibapl_jnhw_common_downcall_jni_JniMi__V___B__L
#define _Included_de_ibapl_jnhw_common_downcall_jni_JniMi__V___B__L
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_common_downcall_jni_JniMi__V___B__L
 * Method:    invoke__V___B__L
 * Signature: (JBJ)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_common_downcall_jni_JniMi_1_1V_1_1_1B_1_1L_invoke_1_1V_1_1_1B_1_1L
  (JNIEnv *, jclass, jlong, jbyte, jlong);

#ifdef __cplusplus
}
#endif
#endif
