/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_downcall_jni_JniMi__S___V */

#ifndef _Included_de_ibapl_jnhw_common_downcall_jni_JniMi__S___V
#define _Included_de_ibapl_jnhw_common_downcall_jni_JniMi__S___V
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_common_downcall_jni_JniMi__S___V
 * Method:    invoke__S___V
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_de_ibapl_jnhw_common_downcall_jni_JniMi_1_1S_1_1_1V_invoke_1_1S_1_1_1V
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
