/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_downcall_jni_JniMi_MA___A__A__L__I */

#ifndef _Included_de_ibapl_jnhw_common_downcall_jni_JniMi_MA___A__A__L__I
#define _Included_de_ibapl_jnhw_common_downcall_jni_JniMi_MA___A__A__L__I
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_common_downcall_jni_JniMi_MA___A__A__L__I
 * Method:    invoke_MA___A__A__L__I
 * Signature: (JJJJI)J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_common_downcall_jni_JniMi_1MA_1_1_1A_1_1A_1_1L_1_1I_invoke_1MA_1_1_1A_1_1A_1_1L_1_1I
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
