/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_downcall_jni_JniMi__V___I */

#ifndef _Included_de_ibapl_jnhw_common_downcall_jni_JniMi__V___I
#define _Included_de_ibapl_jnhw_common_downcall_jni_JniMi__V___I
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_common_downcall_jni_JniMi__V___I
 * Method:    invoke__V___I
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_common_downcall_jni_JniMi_1_1V_1_1_1I_invoke_1_1V_1_1_1I
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
