/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_downcall_jni_JniMi__I___I__L_VARARGS_NONE */

#ifndef _Included_de_ibapl_jnhw_common_downcall_jni_JniMi__I___I__L_VARARGS_NONE
#define _Included_de_ibapl_jnhw_common_downcall_jni_JniMi__I___I__L_VARARGS_NONE
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_common_downcall_jni_JniMi__I___I__L_VARARGS_NONE
 * Method:    invoke__I___I__I
 * Signature: (JIJ)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_common_downcall_jni_JniMi_1_1I_1_1_1I_1_1L_1VARARGS_1NONE_invoke_1_1I_1_1_1I_1_1I
  (JNIEnv *, jclass, jlong, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
