/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_memory_AbstractNativeMemory_MemoryCleaner */

#ifndef _Included_de_ibapl_jnhw_common_memory_AbstractNativeMemory_MemoryCleaner
#define _Included_de_ibapl_jnhw_common_memory_AbstractNativeMemory_MemoryCleaner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_common_memory_AbstractNativeMemory_MemoryCleaner
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_common_memory_AbstractNativeMemory_00024MemoryCleaner_free
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
