/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_callback_Callback_IJ_V */

#ifndef _Included_de_ibapl_jnhw_common_callback_Callback_IJ_V
#define _Included_de_ibapl_jnhw_common_callback_Callback_IJ_V
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_common_callback_Callback_IJ_V
 * Method:    sizeofIntptr_t
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_common_callback_Callback_1IJ_1V_sizeofIntptr_1t
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_common_callback_Callback_IJ_V
 * Method:    alignofIntptr_t
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_common_callback_Callback_1IJ_1V_alignofIntptr_1t
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
