/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_downcall_jni_JniMi__I___I__A__I_VARARGS__S */

#ifndef _Included_de_ibapl_jnhw_common_downcall_jni_JniMi__I___I__A__I_VARARGS__S
#define _Included_de_ibapl_jnhw_common_downcall_jni_JniMi__I___I__A__I_VARARGS__S
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_common_downcall_jni_JniMi__I___I__A__I_VARARGS__S
 * Method:    invoke__I___I__A__I_VARARGS__S
 * Signature: (JIJIS)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_common_downcall_jni_JniMi_1_1I_1_1_1I_1_1A_1_1I_1VARARGS_1_1S_invoke_1_1I_1_1_1I_1_1A_1_1I_1VARARGS_1_1S
  (JNIEnv *, jclass, jlong, jint, jlong, jint, jshort);

#ifdef __cplusplus
}
#endif
#endif
