/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_downcall_jni_JniMi_MA___V */

#ifndef _Included_de_ibapl_jnhw_common_downcall_jni_JniMi_MA___V
#define _Included_de_ibapl_jnhw_common_downcall_jni_JniMi_MA___V
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_common_downcall_jni_JniMi_MA___V
 * Method:    invoke_MA___V
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_common_downcall_jni_JniMi_1MA_1_1_1V_invoke_1MA_1_1_1V
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
