/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_memory_NativeIntNumber */

#ifndef _Included_de_ibapl_jnhw_common_memory_NativeIntNumber
#define _Included_de_ibapl_jnhw_common_memory_NativeIntNumber
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_common_memory_NativeIntNumber
 * Method:    nativeInt8ToHexString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_ibapl_jnhw_common_memory_NativeIntNumber_nativeInt8ToHexString
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_common_memory_NativeIntNumber
 * Method:    nativeInt16ToHexString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_ibapl_jnhw_common_memory_NativeIntNumber_nativeInt16ToHexString
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_common_memory_NativeIntNumber
 * Method:    nativeInt32ToHexString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_ibapl_jnhw_common_memory_NativeIntNumber_nativeInt32ToHexString
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_common_memory_NativeIntNumber
 * Method:    nativeInt64ToHexString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_ibapl_jnhw_common_memory_NativeIntNumber_nativeInt64ToHexString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
