/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_datatypes_BaseDataType */

#ifndef _Included_de_ibapl_jnhw_common_datatypes_BaseDataType
#define _Included_de_ibapl_jnhw_common_datatypes_BaseDataType
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_common_datatypes_BaseDataType
 * Method:    getSizeOfPointer0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_common_datatypes_BaseDataType_getSizeOfPointer0
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_common_datatypes_BaseDataType
 * Method:    getSizeOf_long0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_common_datatypes_BaseDataType_getSizeOf_1long0
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_common_datatypes_BaseDataType
 * Method:    getSizeOf_float0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_common_datatypes_BaseDataType_getSizeOf_1float0
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_common_datatypes_BaseDataType
 * Method:    getSizeOf_double0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_common_datatypes_BaseDataType_getSizeOf_1double0
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_common_datatypes_BaseDataType
 * Method:    getSizeOf_long_double0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_common_datatypes_BaseDataType_getSizeOf_1long_1double0
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
