/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_downcall_jni_JniMi__I___I__L__L__I */

#ifndef _Included_de_ibapl_jnhw_common_downcall_jni_JniMi__I___I__L__L__I
#define _Included_de_ibapl_jnhw_common_downcall_jni_JniMi__I___I__L__L__I
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_common_downcall_jni_JniMi__I___I__L__L__I
 * Method:    invoke__I___I__L__L__I
 * Signature: (JIJJI)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_common_downcall_jni_JniMi_1_1I_1_1_1I_1_1L_1_1L_1_1I_invoke_1_1I_1_1_1I_1_1L_1_1L_1_1I
  (JNIEnv *, jclass, jlong, jint, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
