/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_memory_layout_Alignment */

#ifndef _Included_de_ibapl_jnhw_common_memory_layout_Alignment
#define _Included_de_ibapl_jnhw_common_memory_layout_Alignment
#ifdef __cplusplus
extern "C" {
#endif
#undef de_ibapl_jnhw_common_memory_layout_Alignment_REQ_ALIGNOF_POINTER
#define de_ibapl_jnhw_common_memory_layout_Alignment_REQ_ALIGNOF_POINTER 1L
#undef de_ibapl_jnhw_common_memory_layout_Alignment_REQ_ALIGNOF_LONG
#define de_ibapl_jnhw_common_memory_layout_Alignment_REQ_ALIGNOF_LONG 2L
#undef de_ibapl_jnhw_common_memory_layout_Alignment_REQ___BIGGEST_ALIGNMENT__
#define de_ibapl_jnhw_common_memory_layout_Alignment_REQ___BIGGEST_ALIGNMENT__ 3L
/*
 * Class:     de_ibapl_jnhw_common_memory_layout_Alignment
 * Method:    getFromNative
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_common_memory_layout_Alignment_getFromNative
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
