/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_downcall_jni_JniMi__V___A */

#ifndef _Included_de_ibapl_jnhw_common_downcall_jni_JniMi__V___A
#define _Included_de_ibapl_jnhw_common_downcall_jni_JniMi__V___A
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_common_downcall_jni_JniMi__V___A
 * Method:    invoke__V___A
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_common_downcall_jni_JniMi_1_1V_1_1_1A_invoke_1_1V_1_1_1A
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
