/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_memory_Int8_t */

#ifndef _Included_de_ibapl_jnhw_common_memory_Int8_t
#define _Included_de_ibapl_jnhw_common_memory_Int8_t
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_common_memory_Int8_t
 * Method:    sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_common_memory_Int8_1t_sizeof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_common_memory_Int8_t
 * Method:    alignof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_common_memory_Int8_1t_alignof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_common_memory_Int8_t
 * Method:    rawInt8_t
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_de_ibapl_jnhw_common_memory_Int8_1t_rawInt8_1t__
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_common_memory_Int8_t
 * Method:    rawInt8_t
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_common_memory_Int8_1t_rawInt8_1t__B
  (JNIEnv *, jobject, jbyte);

/*
 * Class:     de_ibapl_jnhw_common_memory_Int8_t
 * Method:    nativeToString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_ibapl_jnhw_common_memory_Int8_1t_nativeToString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
