/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_nativecall_CallNative_Mem_V */

#ifndef _Included_de_ibapl_jnhw_common_nativecall_CallNative_Mem_V
#define _Included_de_ibapl_jnhw_common_nativecall_CallNative_Mem_V
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_common_nativecall_CallNative_Mem_V
 * Method:    call
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_common_nativecall_CallNative_1Mem_1V_call
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
