/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_downcall_jni_JniMi_MA___I__A */

#ifndef _Included_de_ibapl_jnhw_common_downcall_jni_JniMi_MA___I__A
#define _Included_de_ibapl_jnhw_common_downcall_jni_JniMi_MA___I__A
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_common_downcall_jni_JniMi_MA___I__A
 * Method:    invoke_MA___I__A
 * Signature: (JIJ)J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_common_downcall_jni_JniMi_1MA_1_1_1I_1_1A_invoke_1MA_1_1_1I_1_1A
  (JNIEnv *, jclass, jlong, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
