/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_memory_PointerArray32 */

#ifndef _Included_de_ibapl_jnhw_common_memory_PointerArray32
#define _Included_de_ibapl_jnhw_common_memory_PointerArray32
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_common_memory_PointerArray32
 * Method:    get0
 * Signature: (I)Lde/ibapl/jnhw/common/memory/NativeAddressHolder;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_common_memory_PointerArray32_get0
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_ibapl_jnhw_common_memory_PointerArray32
 * Method:    set0
 * Signature: (ILde/ibapl/jnhw/common/memory/OpaqueMemory32;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_common_memory_PointerArray32_set0
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     de_ibapl_jnhw_common_memory_PointerArray32
 * Method:    sizeofPointer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_common_memory_PointerArray32_sizeofPointer
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_common_memory_PointerArray32
 * Method:    alignofPointer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_common_memory_PointerArray32_alignofPointer
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
