/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_downcall_jni_JniMi__I___L */

#ifndef _Included_de_ibapl_jnhw_common_downcall_jni_JniMi__I___L
#define _Included_de_ibapl_jnhw_common_downcall_jni_JniMi__I___L
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_common_downcall_jni_JniMi__I___L
 * Method:    invoke__I___L
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_common_downcall_jni_JniMi_1_1I_1_1_1L_invoke_1_1I_1_1_1L
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
