/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_downcall_jni_JniMi__I___L__I__A */

#ifndef _Included_de_ibapl_jnhw_common_downcall_jni_JniMi__I___L__I__A
#define _Included_de_ibapl_jnhw_common_downcall_jni_JniMi__I___L__I__A
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_common_downcall_jni_JniMi__I___L__I__A
 * Method:    invoke__I___L__I__A
 * Signature: (JJIJ)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_common_downcall_jni_JniMi_1_1I_1_1_1L_1_1I_1_1A_invoke_1_1I_1_1_1L_1_1I_1_1A
  (JNIEnv *, jclass, jlong, jlong, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
