/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_callback_Callback_I_I_Mem_V_Impl */

#ifndef _Included_de_ibapl_jnhw_common_callback_Callback_I_I_Mem_V_Impl
#define _Included_de_ibapl_jnhw_common_callback_Callback_I_I_Mem_V_Impl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_common_callback_Callback_I_I_Mem_V_Impl
 * Method:    initNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_common_callback_Callback_1I_1I_1Mem_1V_1Impl_initNative
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_common_callback_Callback_I_I_Mem_V_Impl
 * Method:    getNativeAddress
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_common_callback_Callback_1I_1I_1Mem_1V_1Impl_getNativeAddress
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_ibapl_jnhw_common_callback_Callback_I_I_Mem_V_Impl
 * Method:    MAX_CALL_BACKS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_common_callback_Callback_1I_1I_1Mem_1V_1Impl_MAX_1CALL_1BACKS
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
