/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_downcall_jni_JniMi__V___V */

#ifndef _Included_de_ibapl_jnhw_common_downcall_jni_JniMi__V___V
#define _Included_de_ibapl_jnhw_common_downcall_jni_JniMi__V___V
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_common_downcall_jni_JniMi__V___V
 * Method:    invoke__V___V
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_common_downcall_jni_JniMi_1_1V_1_1_1V_invoke_1_1V_1_1_1V
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
