/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_memory_Int64_t */

#ifndef _Included_de_ibapl_jnhw_common_memory_Int64_t
#define _Included_de_ibapl_jnhw_common_memory_Int64_t
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_common_memory_Int64_t
 * Method:    sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_common_memory_Int64_1t_sizeof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_common_memory_Int64_t
 * Method:    alignof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_common_memory_Int64_1t_alignof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_common_memory_Int64_t
 * Method:    rawInt64_t
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_common_memory_Int64_1t_rawInt64_1t__
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_common_memory_Int64_t
 * Method:    rawInt64_t
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_common_memory_Int64_1t_rawInt64_1t__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_ibapl_jnhw_common_memory_Int64_t
 * Method:    nativeToString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_ibapl_jnhw_common_memory_Int64_1t_nativeToString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
