/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_callback_NativeRunnable */

#ifndef _Included_de_ibapl_jnhw_common_callback_NativeRunnable
#define _Included_de_ibapl_jnhw_common_callback_NativeRunnable
#ifdef __cplusplus
extern "C" {
#endif
#undef de_ibapl_jnhw_common_callback_NativeRunnable_NULL
#define de_ibapl_jnhw_common_callback_NativeRunnable_NULL 0LL
/*
 * Class:     de_ibapl_jnhw_common_callback_NativeRunnable
 * Method:    aquireObjectRef
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_common_callback_NativeRunnable_aquireObjectRef
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_common_callback_NativeRunnable
 * Method:    releaseObjectRef
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_common_callback_NativeRunnable_releaseObjectRef
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_common_callback_NativeRunnable
 * Method:    sizeOf_ObjectRef
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_common_callback_NativeRunnable_sizeOf_1ObjectRef
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
