/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_TimeTest_NativeDefines */

#ifndef _Included_de_ibapl_jnhw_posix_TimeTest_NativeDefines
#define _Included_de_ibapl_jnhw_posix_TimeTest_NativeDefines
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_TimeTest_NativeDefines
 * Method:    HAVE_TIME_H
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_posix_TimeTest_00024NativeDefines_HAVE_1TIME_1H
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TimeTest_NativeDefines
 * Method:    CLOCKS_PER_SEC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TimeTest_00024NativeDefines_CLOCKS_1PER_1SEC
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TimeTest_NativeDefines
 * Method:    CLOCK_MONOTONIC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TimeTest_00024NativeDefines_CLOCK_1MONOTONIC
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TimeTest_NativeDefines
 * Method:    CLOCK_PROCESS_CPUTIME_ID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TimeTest_00024NativeDefines_CLOCK_1PROCESS_1CPUTIME_1ID
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TimeTest_NativeDefines
 * Method:    CLOCK_REALTIME
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TimeTest_00024NativeDefines_CLOCK_1REALTIME
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TimeTest_NativeDefines
 * Method:    CLOCK_THREAD_CPUTIME_ID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TimeTest_00024NativeDefines_CLOCK_1THREAD_1CPUTIME_1ID
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TimeTest_NativeDefines
 * Method:    TIMER_ABSTIME
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TimeTest_00024NativeDefines_TIMER_1ABSTIME
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
