/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_TimeTest_NativeItimerspec */

#ifndef _Included_de_ibapl_jnhw_posix_TimeTest_NativeItimerspec
#define _Included_de_ibapl_jnhw_posix_TimeTest_NativeItimerspec
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_TimeTest_NativeItimerspec
 * Method:    alignof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TimeTest_00024NativeItimerspec_alignof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TimeTest_NativeItimerspec
 * Method:    sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TimeTest_00024NativeItimerspec_sizeof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TimeTest_NativeItimerspec
 * Method:    it_interval
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_TimeTest_00024NativeItimerspec_it_1interval
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TimeTest_NativeItimerspec
 * Method:    it_value
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_TimeTest_00024NativeItimerspec_it_1value
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
