/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_StdioTest_NativeDefines */

#ifndef _Included_de_ibapl_jnhw_posix_StdioTest_NativeDefines
#define _Included_de_ibapl_jnhw_posix_StdioTest_NativeDefines
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_StdioTest_NativeDefines
 * Method:    HAVE_STDIO_H
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_posix_StdioTest_00024NativeDefines_HAVE_1STDIO_1H
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_StdioTest_NativeDefines
 * Method:    EOF
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_StdioTest_00024NativeDefines_EOF
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_StdioTest_NativeDefines
 * Method:    SEEK_CUR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_StdioTest_00024NativeDefines_SEEK_1CUR
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_StdioTest_NativeDefines
 * Method:    SEEK_END
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_StdioTest_00024NativeDefines_SEEK_1END
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_StdioTest_NativeDefines
 * Method:    SEEK_SET
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_StdioTest_00024NativeDefines_SEEK_1SET
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
