/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_TermiosTest_NativeDefines */

#ifndef _Included_de_ibapl_jnhw_posix_TermiosTest_NativeDefines
#define _Included_de_ibapl_jnhw_posix_TermiosTest_NativeDefines
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    HAVE_TERMIOS_H
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_HAVE_1TERMIOS_1H
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    _HAVE_STRUCT_TERMIOS_C_ISPEED
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines__1HAVE_1STRUCT_1TERMIOS_1C_1ISPEED
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    _HAVE_STRUCT_TERMIOS_C_OSPEED
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines__1HAVE_1STRUCT_1TERMIOS_1C_1OSPEED
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    B0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_B0
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    B1000000
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_B1000000
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    B110
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_B110
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    B115200
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_B115200
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    B1152000
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_B1152000
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    B1200
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_B1200
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    B134
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_B134
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    B150
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_B150
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    B1500000
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_B1500000
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    B1800
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_B1800
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    B19200
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_B19200
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    B200
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_B200
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    B2000000
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_B2000000
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    B230400
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_B230400
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    B2400
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_B2400
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    B2500000
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_B2500000
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    B300
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_B300
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    B3000000
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_B3000000
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    B3500000
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_B3500000
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    B38400
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_B38400
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    B4000000
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_B4000000
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    B460800
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_B460800
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    B4800
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_B4800
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    B50
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_B50
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    B500000
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_B500000
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    B57600
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_B57600
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    B576000
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_B576000
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    B600
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_B600
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    B75
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_B75
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    B921600
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_B921600
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    B9600
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_B9600
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    BRKINT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_BRKINT
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    BS0
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_BS0
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    BS1
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_BS1
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    BSDLY
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_BSDLY
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    CLOCAL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_CLOCAL
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    CMSPAR
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_CMSPAR
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    CR0
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_CR0
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    CR1
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_CR1
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    CR2
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_CR2
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    CR3
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_CR3
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    CRDLY
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_CRDLY
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    CREAD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_CREAD
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    CRTSCTS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_CRTSCTS
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    CS5
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_CS5
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    CS6
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_CS6
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    CS7
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_CS7
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    CS8
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_CS8
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    CSIZE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_CSIZE
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    CSTOPB
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_CSTOPB
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    ECHO
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_ECHO
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    ECHOE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_ECHOE
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    ECHOK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_ECHOK
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    ECHONL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_ECHONL
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    FF0
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_FF0
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    FF1
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_FF1
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    FFDLY
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_FFDLY
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    HUPCL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_HUPCL
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    ICANON
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_ICANON
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    ICRNL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_ICRNL
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    IEXTEN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_IEXTEN
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    IGNBRK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_IGNBRK
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    IGNCR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_IGNCR
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    IGNPAR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_IGNPAR
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    INLCR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_INLCR
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    INPCK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_INPCK
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    ISIG
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_ISIG
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    ISTRIP
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_ISTRIP
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    IXANY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_IXANY
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    IXOFF
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_IXOFF
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    IXON
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_IXON
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    NCCS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_NCCS
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    NL0
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_NL0
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    NL1
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_NL1
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    NLDLY
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_NLDLY
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    NOFLSH
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_NOFLSH
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    OCRNL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_OCRNL
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    OFDEL
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_OFDEL
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    OFILL
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_OFILL
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    ONLCR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_ONLCR
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    ONLRET
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_ONLRET
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    ONOCR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_ONOCR
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    OPOST
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_OPOST
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    PARENB
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_PARENB
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    PAREXT
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_PAREXT
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    PARMRK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_PARMRK
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    PARODD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_PARODD
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    TAB0
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_TAB0
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    TAB1
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_TAB1
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    TAB2
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_TAB2
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    TAB3
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_TAB3
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    TABDLY
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_TABDLY
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    TCIFLUSH
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_TCIFLUSH
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    TCIOFF
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_TCIOFF
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    TCIOFLUSH
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_TCIOFLUSH
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    TCION
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_TCION
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    TCOFLUSH
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_TCOFLUSH
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    TCOOFF
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_TCOOFF
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    TCOON
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_TCOON
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    TCSADRAIN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_TCSADRAIN
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    TCSAFLUSH
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_TCSAFLUSH
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    TCSANOW
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_TCSANOW
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    TOSTOP
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_TOSTOP
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    VEOF
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_VEOF
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    VEOL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_VEOL
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    VERASE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_VERASE
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    VINTR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_VINTR
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    VKILL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_VKILL
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    VMIN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_VMIN
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    VQUIT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_VQUIT
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    VSTART
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_VSTART
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    VSTOP
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_VSTOP
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    VSUSP
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_VSUSP
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    VT0
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_VT0
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    VT1
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_VT1
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    VTDLY
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_VTDLY
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeDefines
 * Method:    VTIME
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeDefines_VTIME
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
