/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_PthreadTest_NativeDefines */

#ifndef _Included_de_ibapl_jnhw_posix_PthreadTest_NativeDefines
#define _Included_de_ibapl_jnhw_posix_PthreadTest_NativeDefines
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_PthreadTest_NativeDefines
 * Method:    HAVE_PTHREAD_H
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_posix_PthreadTest_00024NativeDefines_HAVE_1PTHREAD_1H
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_PthreadTest_NativeDefines
 * Method:    PTHREAD_EXPLICIT_SCHED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_PthreadTest_00024NativeDefines_PTHREAD_1EXPLICIT_1SCHED
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_PthreadTest_NativeDefines
 * Method:    PTHREAD_INHERIT_SCHED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_PthreadTest_00024NativeDefines_PTHREAD_1INHERIT_1SCHED
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_PthreadTest_NativeDefines
 * Method:    PTHREAD_CANCEL_DISABLE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_PthreadTest_00024NativeDefines_PTHREAD_1CANCEL_1DISABLE
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_PthreadTest_NativeDefines
 * Method:    PTHREAD_CANCEL_ENABLE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_PthreadTest_00024NativeDefines_PTHREAD_1CANCEL_1ENABLE
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_PthreadTest_NativeDefines
 * Method:    PTHREAD_CANCEL_DEFERRED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_PthreadTest_00024NativeDefines_PTHREAD_1CANCEL_1DEFERRED
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_PthreadTest_NativeDefines
 * Method:    PTHREAD_CANCEL_ASYNCHRONOUS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_PthreadTest_00024NativeDefines_PTHREAD_1CANCEL_1ASYNCHRONOUS
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
