/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_SchedTest_NativeSched_param */

#ifndef _Included_de_ibapl_jnhw_posix_SchedTest_NativeSched_param
#define _Included_de_ibapl_jnhw_posix_SchedTest_NativeSched_param
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_SchedTest_NativeSched_param
 * Method:    alignof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SchedTest_00024NativeSched_1param_alignof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SchedTest_NativeSched_param
 * Method:    sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SchedTest_00024NativeSched_1param_sizeof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SchedTest_NativeSched_param
 * Method:    sched_priority
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_SchedTest_00024NativeSched_1param_sched_1priority
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SchedTest_NativeSched_param
 * Method:    sched_ss_low_priority
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_SchedTest_00024NativeSched_1param_sched_1ss_1low_1priority
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SchedTest_NativeSched_param
 * Method:    sched_ss_repl_period
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_SchedTest_00024NativeSched_1param_sched_1ss_1repl_1period
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SchedTest_NativeSched_param
 * Method:    sched_ss_init_budget
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_SchedTest_00024NativeSched_1param_sched_1ss_1init_1budget
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SchedTest_NativeSched_param
 * Method:    sched_ss_max_repl
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_SchedTest_00024NativeSched_1param_sched_1ss_1max_1repl
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
