/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_SignalTest_NativeSigaction */

#ifndef _Included_de_ibapl_jnhw_posix_SignalTest_NativeSigaction
#define _Included_de_ibapl_jnhw_posix_SignalTest_NativeSigaction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeSigaction
 * Method:    alignof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeSigaction_alignof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeSigaction
 * Method:    sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeSigaction_sizeof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeSigaction
 * Method:    sa_handler
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeSigaction_sa_1handler
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeSigaction
 * Method:    sa_mask
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeSigaction_sa_1mask
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeSigaction
 * Method:    sa_flags
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeSigaction_sa_1flags
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeSigaction
 * Method:    sa_sigaction
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeSigaction_sa_1sigaction
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
