/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_SchedTest_NativeDefines */

#ifndef _Included_de_ibapl_jnhw_posix_SchedTest_NativeDefines
#define _Included_de_ibapl_jnhw_posix_SchedTest_NativeDefines
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_SchedTest_NativeDefines
 * Method:    HAVE_SCHED_H
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_posix_SchedTest_00024NativeDefines_HAVE_1SCHED_1H
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SchedTest_NativeDefines
 * Method:    SCHED_FIFO
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SchedTest_00024NativeDefines_SCHED_1FIFO
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SchedTest_NativeDefines
 * Method:    SCHED_OTHER
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SchedTest_00024NativeDefines_SCHED_1OTHER
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SchedTest_NativeDefines
 * Method:    SCHED_RR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SchedTest_00024NativeDefines_SCHED_1RR
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SchedTest_NativeDefines
 * Method:    SCHED_SPORADIC
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_SchedTest_00024NativeDefines_SCHED_1SPORADIC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
