/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_SignalTest_NativeSiginfo_t */

#ifndef _Included_de_ibapl_jnhw_posix_SignalTest_NativeSiginfo_t
#define _Included_de_ibapl_jnhw_posix_SignalTest_NativeSiginfo_t
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeSiginfo_t
 * Method:    alignof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeSiginfo_1t_alignof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeSiginfo_t
 * Method:    sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeSiginfo_1t_sizeof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeSiginfo_t
 * Method:    si_signo
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeSiginfo_1t_si_1signo
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeSiginfo_t
 * Method:    si_code
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeSiginfo_1t_si_1code
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeSiginfo_t
 * Method:    si_errno
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeSiginfo_1t_si_1errno
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeSiginfo_t
 * Method:    si_pid
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeSiginfo_1t_si_1pid
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeSiginfo_t
 * Method:    si_uid
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeSiginfo_1t_si_1uid
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeSiginfo_t
 * Method:    si_addr
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeSiginfo_1t_si_1addr
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeSiginfo_t
 * Method:    si_status
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeSiginfo_1t_si_1status
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeSiginfo_t
 * Method:    si_band
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeSiginfo_1t_si_1band
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeSiginfo_t
 * Method:    si_value
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeSiginfo_1t_si_1value
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
