/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_SignalTest_NativeDefines */

#ifndef _Included_de_ibapl_jnhw_posix_SignalTest_NativeDefines
#define _Included_de_ibapl_jnhw_posix_SignalTest_NativeDefines
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    HAVE_SIGNAL_H
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_HAVE_1SIGNAL_1H
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    ILL_ILLOPC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_ILL_1ILLOPC
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    ILL_ILLOPN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_ILL_1ILLOPN
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    ILL_ILLADR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_ILL_1ILLADR
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    ILL_ILLTRP
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_ILL_1ILLTRP
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    ILL_PRVOPC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_ILL_1PRVOPC
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    ILL_PRVREG
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_ILL_1PRVREG
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    ILL_COPROC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_ILL_1COPROC
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    ILL_BADSTK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_ILL_1BADSTK
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    FPE_INTDIV
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_FPE_1INTDIV
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    FPE_INTOVF
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_FPE_1INTOVF
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    FPE_FLTDIV
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_FPE_1FLTDIV
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    FPE_FLTOVF
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_FPE_1FLTOVF
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    FPE_FLTUND
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_FPE_1FLTUND
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    FPE_FLTRES
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_FPE_1FLTRES
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    FPE_FLTINV
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_FPE_1FLTINV
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    FPE_FLTSUB
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_FPE_1FLTSUB
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SEGV_MAPERR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SEGV_1MAPERR
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SEGV_ACCERR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SEGV_1ACCERR
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    BUS_ADRALN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_BUS_1ADRALN
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    BUS_ADRERR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_BUS_1ADRERR
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    BUS_OBJERR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_BUS_1OBJERR
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    TRAP_BRKPT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_TRAP_1BRKPT
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    TRAP_TRACE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_TRAP_1TRACE
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    CLD_EXITED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_CLD_1EXITED
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    CLD_KILLED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_CLD_1KILLED
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    CLD_DUMPED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_CLD_1DUMPED
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    CLD_TRAPPED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_CLD_1TRAPPED
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    CLD_STOPPED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_CLD_1STOPPED
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    CLD_CONTINUED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_CLD_1CONTINUED
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    POLL_IN
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_POLL_1IN
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    POLL_OUT
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_POLL_1OUT
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    POLL_MSG
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_POLL_1MSG
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    POLL_ERR
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_POLL_1ERR
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    POLL_PRI
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_POLL_1PRI
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    POLL_HUP
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_POLL_1HUP
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SI_USER
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SI_1USER
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SI_QUEUE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SI_1QUEUE
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SI_TIMER
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SI_1TIMER
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SI_ASYNCIO
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SI_1ASYNCIO
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SI_MESGQ
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SI_1MESGQ
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SIG_BLOCK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SIG_1BLOCK
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SIG_UNBLOCK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SIG_1UNBLOCK
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SIG_SETMASK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SIG_1SETMASK
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SA_NOCLDSTOP
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SA_1NOCLDSTOP
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SA_ONSTACK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SA_1ONSTACK
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SA_RESETHAND
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SA_1RESETHAND
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SA_RESTART
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SA_1RESTART
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SA_SIGINFO
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SA_1SIGINFO
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SA_NOCLDWAIT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SA_1NOCLDWAIT
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SA_NODEFER
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SA_1NODEFER
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SS_ONSTACK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SS_1ONSTACK
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SS_DISABLE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SS_1DISABLE
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    MINSIGSTKSZ
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_MINSIGSTKSZ
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SIGSTKSZ
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SIGSTKSZ
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SIG_DFL0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SIG_1DFL0
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SIG_ERR0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SIG_1ERR0
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SIG_HOLD0
 * Signature: ()Ljava/lang/Long;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SIG_1HOLD0
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SIG_IGN0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SIG_1IGN0
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SIGEV_NONE
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SIGEV_1NONE
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SIGEV_SIGNAL
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SIGEV_1SIGNAL
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SIGEV_THREAD
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SIGEV_1THREAD
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SIGABRT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SIGABRT
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SIGALRM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SIGALRM
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SIGBUS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SIGBUS
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SIGCHLD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SIGCHLD
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SIGCONT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SIGCONT
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SIGFPE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SIGFPE
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SIGHUP
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SIGHUP
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SIGILL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SIGILL
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SIGINT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SIGINT
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SIGKILL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SIGKILL
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SIGPIPE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SIGPIPE
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SIGQUIT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SIGQUIT
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SIGSEGV
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SIGSEGV
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SIGSTOP
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SIGSTOP
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SIGTERM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SIGTERM
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SIGTSTP
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SIGTSTP
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SIGTTIN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SIGTTIN
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SIGTTOU
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SIGTTOU
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SIGUSR1
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SIGUSR1
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SIGUSR2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SIGUSR2
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SIGPOLL
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SIGPOLL
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SIGPROF
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SIGPROF
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SIGSYS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SIGSYS
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SIGTRAP
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SIGTRAP
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SIGURG
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SIGURG
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SIGVTALRM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SIGVTALRM
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SIGXCPU
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SIGXCPU
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeDefines
 * Method:    SIGXFSZ
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeDefines_SIGXFSZ
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
