/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_TimeTest_NativeTm */

#ifndef _Included_de_ibapl_jnhw_posix_TimeTest_NativeTm
#define _Included_de_ibapl_jnhw_posix_TimeTest_NativeTm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_TimeTest_NativeTm
 * Method:    alignof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TimeTest_00024NativeTm_alignof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TimeTest_NativeTm
 * Method:    sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TimeTest_00024NativeTm_sizeof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TimeTest_NativeTm
 * Method:    tm_sec
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_TimeTest_00024NativeTm_tm_1sec
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TimeTest_NativeTm
 * Method:    tm_min
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_TimeTest_00024NativeTm_tm_1min
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TimeTest_NativeTm
 * Method:    tm_hour
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_TimeTest_00024NativeTm_tm_1hour
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TimeTest_NativeTm
 * Method:    tm_mday
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_TimeTest_00024NativeTm_tm_1mday
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TimeTest_NativeTm
 * Method:    tm_mon
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_TimeTest_00024NativeTm_tm_1mon
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TimeTest_NativeTm
 * Method:    tm_year
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_TimeTest_00024NativeTm_tm_1year
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TimeTest_NativeTm
 * Method:    tm_wday
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_TimeTest_00024NativeTm_tm_1wday
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TimeTest_NativeTm
 * Method:    tm_yday
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_TimeTest_00024NativeTm_tm_1yday
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TimeTest_NativeTm
 * Method:    tm_isdst
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_TimeTest_00024NativeTm_tm_1isdst
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
