/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines */

#ifndef _Included_de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
#define _Included_de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
 * Method:    _BSD_SOURCE
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_util_posix_DefinesTest_00024NativeDefines__1BSD_1SOURCE
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
 * Method:    _FILE_OFFSET_BITS
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_util_posix_DefinesTest_00024NativeDefines__1FILE_1OFFSET_1BITS
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
 * Method:    _LARGEFILE64_SOURCE
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_util_posix_DefinesTest_00024NativeDefines__1LARGEFILE64_1SOURCE
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
 * Method:    _LARGEFILE_SOURCE
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_util_posix_DefinesTest_00024NativeDefines__1LARGEFILE_1SOURCE
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
 * Method:    _POSIX_C_SOURCE
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_util_posix_DefinesTest_00024NativeDefines__1POSIX_1C_1SOURCE
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
 * Method:    _XOPEN_SOURCE
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_util_posix_DefinesTest_00024NativeDefines__1XOPEN_1SOURCE
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
 * Method:    _XOPEN_SOURCE_EXTENDED
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_util_posix_DefinesTest_00024NativeDefines__1XOPEN_1SOURCE_1EXTENDED
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
 * Method:    __aarch64__
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_util_posix_DefinesTest_00024NativeDefines__1_1aarch64_1_1
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
 * Method:    __alpha__
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_util_posix_DefinesTest_00024NativeDefines__1_1alpha_1_1
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
 * Method:    __amd64__
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_util_posix_DefinesTest_00024NativeDefines__1_1amd64_1_1
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
 * Method:    __APPLE__
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_util_posix_DefinesTest_00024NativeDefines__1_1APPLE_1_1
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
 * Method:    __arm__
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_util_posix_DefinesTest_00024NativeDefines__1_1arm_1_1
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
 * Method:    __ARM_ARCH
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_util_posix_DefinesTest_00024NativeDefines__1_1ARM_1ARCH
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
 * Method:    __BIGGEST_ALIGNMENT__
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_util_posix_DefinesTest_00024NativeDefines__1_1BIGGEST_1ALIGNMENT_1_1
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
 * Method:    __BYTE_ORDER__
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_util_posix_DefinesTest_00024NativeDefines__1_1BYTE_1ORDER_1_1
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
 * Method:    __FreeBSD__
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_util_posix_DefinesTest_00024NativeDefines__1_1FreeBSD_1_1
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
 * Method:    __GLIBC_MINOR__
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_util_posix_DefinesTest_00024NativeDefines__1_1GLIBC_1MINOR_1_1
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
 * Method:    __GLIBC__
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_util_posix_DefinesTest_00024NativeDefines__1_1GLIBC_1_1
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
 * Method:    __GNU_LIBRARY__
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_util_posix_DefinesTest_00024NativeDefines__1_1GNU_1LIBRARY_1_1
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
 * Method:    __i386__
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_util_posix_DefinesTest_00024NativeDefines__1_1i386_1_1
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
 * Method:    __i686__
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_util_posix_DefinesTest_00024NativeDefines__1_1i686_1_1
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
 * Method:    __ILP32__
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_util_posix_DefinesTest_00024NativeDefines__1_1ILP32_1_1
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
 * Method:    __linux__
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_util_posix_DefinesTest_00024NativeDefines__1_1linux_1_1
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
 * Method:    __LP64__
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_util_posix_DefinesTest_00024NativeDefines__1_1LP64_1_1
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
 * Method:    __mips__
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_util_posix_DefinesTest_00024NativeDefines__1_1mips_1_1
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
 * Method:    __mips64
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_util_posix_DefinesTest_00024NativeDefines__1_1mips64
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
 * Method:    __MIPSEB__
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_util_posix_DefinesTest_00024NativeDefines__1_1MIPSEB_1_1
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
 * Method:    __MIPSEL__
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_util_posix_DefinesTest_00024NativeDefines__1_1MIPSEL_1_1
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
 * Method:    __ORDER_BIG_ENDIAN__
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_util_posix_DefinesTest_00024NativeDefines__1_1ORDER_1BIG_1ENDIAN_1_1
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
 * Method:    __ORDER_LITTLE_ENDIAN__
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_util_posix_DefinesTest_00024NativeDefines__1_1ORDER_1LITTLE_1ENDIAN_1_1
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
 * Method:    __ORDER_PDP_ENDIAN__
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_util_posix_DefinesTest_00024NativeDefines__1_1ORDER_1PDP_1ENDIAN_1_1
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
 * Method:    __OpenBSD__
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_util_posix_DefinesTest_00024NativeDefines__1_1OpenBSD_1_1
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
 * Method:    __powerpc__
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_util_posix_DefinesTest_00024NativeDefines__1_1powerpc_1_1
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
 * Method:    __powerpc64__
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_util_posix_DefinesTest_00024NativeDefines__1_1powerpc64_1_1
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
 * Method:    __riscv
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_util_posix_DefinesTest_00024NativeDefines__1_1riscv
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
 * Method:    __SH4__
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_util_posix_DefinesTest_00024NativeDefines__1_1SH4_1_1
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
 * Method:    __SIZEOF_LONG__
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_util_posix_DefinesTest_00024NativeDefines__1_1SIZEOF_1LONG_1_1
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
 * Method:    __SIZEOF_POINTER__
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_util_posix_DefinesTest_00024NativeDefines__1_1SIZEOF_1POINTER_1_1
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
 * Method:    __s390__
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_util_posix_DefinesTest_00024NativeDefines__1_1s390_1_1
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
 * Method:    __s390x__
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_util_posix_DefinesTest_00024NativeDefines__1_1s390x_1_1
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
 * Method:    __sh__
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_util_posix_DefinesTest_00024NativeDefines__1_1sh_1_1
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
 * Method:    __sparc64__
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_util_posix_DefinesTest_00024NativeDefines__1_1sparc64_1_1
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
 * Method:    __sparc__
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_util_posix_DefinesTest_00024NativeDefines__1_1sparc_1_1
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
 * Method:    __TIMESIZE
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_util_posix_DefinesTest_00024NativeDefines__1_1TIMESIZE
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
 * Method:    __WORDSIZE
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_util_posix_DefinesTest_00024NativeDefines__1_1WORDSIZE
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_DefinesTest_NativeDefines
 * Method:    __x86_64__
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_util_posix_DefinesTest_00024NativeDefines__1_1x86_164_1_1
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
