/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_SignalTest_NativeSigevent */

#ifndef _Included_de_ibapl_jnhw_posix_SignalTest_NativeSigevent
#define _Included_de_ibapl_jnhw_posix_SignalTest_NativeSigevent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeSigevent
 * Method:    alignof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeSigevent_alignof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeSigevent
 * Method:    sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeSigevent_sizeof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeSigevent
 * Method:    sigev_notify
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeSigevent_sigev_1notify
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeSigevent
 * Method:    sigev_signo
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeSigevent_sigev_1signo
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeSigevent
 * Method:    sigev_value
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeSigevent_sigev_1value
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeSigevent
 * Method:    sigev_notify_function
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeSigevent_sigev_1notify_1function
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeSigevent
 * Method:    sigev_notify_attributes
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeSigevent_sigev_1notify_1attributes
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
