/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_LocaleTest_NativeDefines */

#ifndef _Included_de_ibapl_jnhw_posix_LocaleTest_NativeDefines
#define _Included_de_ibapl_jnhw_posix_LocaleTest_NativeDefines
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_LocaleTest_NativeDefines
 * Method:    HAVE_LOCALE_H
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_posix_LocaleTest_00024NativeDefines_HAVE_1LOCALE_1H
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_LocaleTest_NativeDefines
 * Method:    LC_ALL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_LocaleTest_00024NativeDefines_LC_1ALL
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_LocaleTest_NativeDefines
 * Method:    LC_ALL_MASK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_LocaleTest_00024NativeDefines_LC_1ALL_1MASK
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_LocaleTest_NativeDefines
 * Method:    LC_COLLATE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_LocaleTest_00024NativeDefines_LC_1COLLATE
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_LocaleTest_NativeDefines
 * Method:    LC_COLLATE_MASK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_LocaleTest_00024NativeDefines_LC_1COLLATE_1MASK
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_LocaleTest_NativeDefines
 * Method:    LC_CTYPE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_LocaleTest_00024NativeDefines_LC_1CTYPE
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_LocaleTest_NativeDefines
 * Method:    LC_CTYPE_MASK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_LocaleTest_00024NativeDefines_LC_1CTYPE_1MASK
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_LocaleTest_NativeDefines
 * Method:    LC_GLOBAL_LOCALE0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_LocaleTest_00024NativeDefines_LC_1GLOBAL_1LOCALE0
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_LocaleTest_NativeDefines
 * Method:    LC_MESSAGES
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_LocaleTest_00024NativeDefines_LC_1MESSAGES
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_LocaleTest_NativeDefines
 * Method:    LC_MESSAGES_MASK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_LocaleTest_00024NativeDefines_LC_1MESSAGES_1MASK
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_LocaleTest_NativeDefines
 * Method:    LC_MONETARY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_LocaleTest_00024NativeDefines_LC_1MONETARY
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_LocaleTest_NativeDefines
 * Method:    LC_MONETARY_MASK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_LocaleTest_00024NativeDefines_LC_1MONETARY_1MASK
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_LocaleTest_NativeDefines
 * Method:    LC_NUMERIC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_LocaleTest_00024NativeDefines_LC_1NUMERIC
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_LocaleTest_NativeDefines
 * Method:    LC_NUMERIC_MASK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_LocaleTest_00024NativeDefines_LC_1NUMERIC_1MASK
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_LocaleTest_NativeDefines
 * Method:    LC_TIME
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_LocaleTest_00024NativeDefines_LC_1TIME
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_LocaleTest_NativeDefines
 * Method:    LC_TIME_MASK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_LocaleTest_00024NativeDefines_LC_1TIME_1MASK
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
