/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_SignalTest_NativeSigval */

#ifndef _Included_de_ibapl_jnhw_posix_SignalTest_NativeSigval
#define _Included_de_ibapl_jnhw_posix_SignalTest_NativeSigval
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeSigval
 * Method:    alignof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeSigval_alignof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeSigval
 * Method:    sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeSigval_sizeof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeSigval
 * Method:    sival_int
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeSigval_sival_1int
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_SignalTest_NativeSigval
 * Method:    sival_ptr
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_SignalTest_00024NativeSigval_sival_1ptr
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
