/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_TimeTest_NativeTimerspec */

#ifndef _Included_de_ibapl_jnhw_posix_TimeTest_NativeTimerspec
#define _Included_de_ibapl_jnhw_posix_TimeTest_NativeTimerspec
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_TimeTest_NativeTimerspec
 * Method:    alignof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TimeTest_00024NativeTimerspec_alignof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TimeTest_NativeTimerspec
 * Method:    sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TimeTest_00024NativeTimerspec_sizeof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TimeTest_NativeTimerspec
 * Method:    tv_sec
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_TimeTest_00024NativeTimerspec_tv_1sec
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TimeTest_NativeTimerspec
 * Method:    tv_nsec
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_TimeTest_00024NativeTimerspec_tv_1nsec
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
