/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_isoc_ErrnoTest_NativeDefines */

#ifndef _Included_de_ibapl_jnhw_isoc_ErrnoTest_NativeDefines
#define _Included_de_ibapl_jnhw_isoc_ErrnoTest_NativeDefines
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_isoc_ErrnoTest_NativeDefines
 * Method:    HAVE_ERRNO_H
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_isoc_ErrnoTest_00024NativeDefines_HAVE_1ERRNO_1H
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_isoc_ErrnoTest_NativeDefines
 * Method:    EDOM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_isoc_ErrnoTest_00024NativeDefines_EDOM
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_isoc_ErrnoTest_NativeDefines
 * Method:    EILSEQ
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_isoc_ErrnoTest_00024NativeDefines_EILSEQ
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_isoc_ErrnoTest_NativeDefines
 * Method:    ERANGE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_isoc_ErrnoTest_00024NativeDefines_ERANGE
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
