/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines */

#ifndef _Included_de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
#define _Included_de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    HAVE_SYS_IOCTL_H
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines_HAVE_1SYS_1IOCTL_1H
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    FIONREAD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines_FIONREAD
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    TIOCCBRK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines_TIOCCBRK
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    TIOCEXCL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines_TIOCEXCL
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    TIOCGICOUNT
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines_TIOCGICOUNT
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    TIOCGSOFTCAR
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines_TIOCGSOFTCAR
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    TIOCMBIC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines_TIOCMBIC
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    TIOCMBIS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines_TIOCMBIS
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    TIOCMGET
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines_TIOCMGET
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    TIOCMIWAIT
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines_TIOCMIWAIT
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    TIOCMSET
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines_TIOCMSET
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    TIOCM_CAR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines_TIOCM_1CAR
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    TIOCM_CD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines_TIOCM_1CD
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    TIOCM_CTS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines_TIOCM_1CTS
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    TIOCM_DSR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines_TIOCM_1DSR
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    TIOCM_DTR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines_TIOCM_1DTR
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    TIOCM_LE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines_TIOCM_1LE
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    TIOCM_RI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines_TIOCM_1RI
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    TIOCM_RNG
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines_TIOCM_1RNG
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    TIOCM_RTS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines_TIOCM_1RTS
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    TIOCM_SR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines_TIOCM_1SR
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    TIOCM_ST
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines_TIOCM_1ST
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    TIOCOUTQ
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines_TIOCOUTQ
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    TIOCSBRK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines_TIOCSBRK
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    TIOCSSOFTCAR
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines_TIOCSSOFTCAR
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    IOCPARM_MASK
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines_IOCPARM_1MASK
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    IOCPARM_MAX
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines_IOCPARM_1MAX
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    IOC_VOID
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines_IOC_1VOID
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    IOC_OUT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines_IOC_1OUT
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    IOC_IN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines_IOC_1IN
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    IOC_INOUT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines_IOC_1INOUT
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    IOC_DIRMASK
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines_IOC_1DIRMASK
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    _IOC_NRBITS
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines__1IOC_1NRBITS
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    _IOC_TYPEBITS
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines__1IOC_1TYPEBITS
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    _IOC_SIZEBITS
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines__1IOC_1SIZEBITS
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    _IOC_DIRBITS
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines__1IOC_1DIRBITS
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    _IOC_NRMASK
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines__1IOC_1NRMASK
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    _IOC_TYPEMASK
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines__1IOC_1TYPEMASK
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    _IOC_SIZEMASK
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines__1IOC_1SIZEMASK
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    _IOC_DIRMASK
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines__1IOC_1DIRMASK
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    _IOC_NRSHIFT
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines__1IOC_1NRSHIFT
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    _IOC_TYPESHIFT
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines__1IOC_1TYPESHIFT
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    _IOC_SIZESHIFT
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines__1IOC_1SIZESHIFT
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    _IOC_DIRSHIFT
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines__1IOC_1DIRSHIFT
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    _IOC_NONE
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines__1IOC_1NONE
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    _IOC_READ
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines__1IOC_1READ
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    _IOC_WRITE
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines__1IOC_1WRITE
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    IOCSIZE_MASK
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines_IOCSIZE_1MASK
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_unix_sys_IoctlTest_NativeDefines
 * Method:    IOCSIZE_SHIFT
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_unix_sys_IoctlTest_00024NativeDefines_IOCSIZE_1SHIFT
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
