/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_LocaleTest */

#ifndef _Included_de_ibapl_jnhw_posix_LocaleTest
#define _Included_de_ibapl_jnhw_posix_LocaleTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_LocaleTest
 * Method:    testNativelyLC_GLOBAL_LOCALE
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_LocaleTest_testNativelyLC_1GLOBAL_1LOCALE
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
