/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_AioTest_NativeAiocb */

#ifndef _Included_de_ibapl_jnhw_posix_AioTest_NativeAiocb
#define _Included_de_ibapl_jnhw_posix_AioTest_NativeAiocb
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_AioTest_NativeAiocb
 * Method:    alignof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_AioTest_00024NativeAiocb_alignof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_AioTest_NativeAiocb
 * Method:    sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_AioTest_00024NativeAiocb_sizeof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_AioTest_NativeAiocb
 * Method:    aio_fildes
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_AioTest_00024NativeAiocb_aio_1fildes
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_AioTest_NativeAiocb
 * Method:    aio_offset
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_AioTest_00024NativeAiocb_aio_1offset
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_AioTest_NativeAiocb
 * Method:    aio_buf
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_AioTest_00024NativeAiocb_aio_1buf
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_AioTest_NativeAiocb
 * Method:    aio_nbytes
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_AioTest_00024NativeAiocb_aio_1nbytes
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_AioTest_NativeAiocb
 * Method:    aio_reqprio
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_AioTest_00024NativeAiocb_aio_1reqprio
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_AioTest_NativeAiocb
 * Method:    aio_sigevent
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_AioTest_00024NativeAiocb_aio_1sigevent
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_AioTest_NativeAiocb
 * Method:    aio_lio_opcode
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_AioTest_00024NativeAiocb_aio_1lio_1opcode
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
