/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_AioTest_NativeDefines */

#ifndef _Included_de_ibapl_jnhw_posix_AioTest_NativeDefines
#define _Included_de_ibapl_jnhw_posix_AioTest_NativeDefines
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_AioTest_NativeDefines
 * Method:    HAVE_AIO_H
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_posix_AioTest_00024NativeDefines_HAVE_1AIO_1H
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_AioTest_NativeDefines
 * Method:    AIO_ALLDONE
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_AioTest_00024NativeDefines_AIO_1ALLDONE
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_AioTest_NativeDefines
 * Method:    AIO_CANCELED
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_AioTest_00024NativeDefines_AIO_1CANCELED
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_AioTest_NativeDefines
 * Method:    AIO_NOTCANCELED
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_AioTest_00024NativeDefines_AIO_1NOTCANCELED
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_AioTest_NativeDefines
 * Method:    LIO_NOP
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_AioTest_00024NativeDefines_LIO_1NOP
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_AioTest_NativeDefines
 * Method:    LIO_NOWAIT
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_AioTest_00024NativeDefines_LIO_1NOWAIT
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_AioTest_NativeDefines
 * Method:    LIO_READ
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_AioTest_00024NativeDefines_LIO_1READ
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_AioTest_NativeDefines
 * Method:    LIO_WAIT
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_AioTest_00024NativeDefines_LIO_1WAIT
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_AioTest_NativeDefines
 * Method:    LIO_WRITE
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_AioTest_00024NativeDefines_LIO_1WRITE
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
