/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_sys_StatTest_NativeDefines */

#ifndef _Included_de_ibapl_jnhw_posix_sys_StatTest_NativeDefines
#define _Included_de_ibapl_jnhw_posix_sys_StatTest_NativeDefines
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_sys_StatTest_NativeDefines
 * Method:    HAVE_SYS_STAT_H
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_posix_sys_StatTest_00024NativeDefines_HAVE_1SYS_1STAT_1H
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_sys_StatTest_NativeDefines
 * Method:    S_IRGRP
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_sys_StatTest_00024NativeDefines_S_1IRGRP
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_sys_StatTest_NativeDefines
 * Method:    S_IROTH
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_sys_StatTest_00024NativeDefines_S_1IROTH
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_sys_StatTest_NativeDefines
 * Method:    S_IRUSR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_sys_StatTest_00024NativeDefines_S_1IRUSR
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_sys_StatTest_NativeDefines
 * Method:    S_IRWXG
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_sys_StatTest_00024NativeDefines_S_1IRWXG
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_sys_StatTest_NativeDefines
 * Method:    S_IRWXO
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_sys_StatTest_00024NativeDefines_S_1IRWXO
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_sys_StatTest_NativeDefines
 * Method:    S_IRWXU
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_sys_StatTest_00024NativeDefines_S_1IRWXU
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_sys_StatTest_NativeDefines
 * Method:    S_ISGID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_sys_StatTest_00024NativeDefines_S_1ISGID
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_sys_StatTest_NativeDefines
 * Method:    S_ISUID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_sys_StatTest_00024NativeDefines_S_1ISUID
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_sys_StatTest_NativeDefines
 * Method:    S_ISVTX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_sys_StatTest_00024NativeDefines_S_1ISVTX
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_sys_StatTest_NativeDefines
 * Method:    S_IWGRP
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_sys_StatTest_00024NativeDefines_S_1IWGRP
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_sys_StatTest_NativeDefines
 * Method:    S_IWOTH
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_sys_StatTest_00024NativeDefines_S_1IWOTH
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_sys_StatTest_NativeDefines
 * Method:    S_IWUSR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_sys_StatTest_00024NativeDefines_S_1IWUSR
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_sys_StatTest_NativeDefines
 * Method:    S_IXGRP
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_sys_StatTest_00024NativeDefines_S_1IXGRP
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_sys_StatTest_NativeDefines
 * Method:    S_IXOTH
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_sys_StatTest_00024NativeDefines_S_1IXOTH
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_sys_StatTest_NativeDefines
 * Method:    S_IXUSR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_sys_StatTest_00024NativeDefines_S_1IXUSR
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
