/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_UnistdTest_NativeDefines */

#ifndef _Included_de_ibapl_jnhw_posix_UnistdTest_NativeDefines
#define _Included_de_ibapl_jnhw_posix_UnistdTest_NativeDefines
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_UnistdTest_NativeDefines
 * Method:    HAVE_UNISTD_H
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_posix_UnistdTest_00024NativeDefines_HAVE_1UNISTD_1H
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_UnistdTest_NativeDefines
 * Method:    _POSIX_VERSION
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_UnistdTest_00024NativeDefines__1POSIX_1VERSION
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_UnistdTest_NativeDefines
 * Method:    SEEK_CUR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_UnistdTest_00024NativeDefines_SEEK_1CUR
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_UnistdTest_NativeDefines
 * Method:    SEEK_DATA
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_UnistdTest_00024NativeDefines_SEEK_1DATA
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_UnistdTest_NativeDefines
 * Method:    SEEK_END
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_UnistdTest_00024NativeDefines_SEEK_1END
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_UnistdTest_NativeDefines
 * Method:    SEEK_HOLE
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_UnistdTest_00024NativeDefines_SEEK_1HOLE
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_UnistdTest_NativeDefines
 * Method:    SEEK_SET
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_UnistdTest_00024NativeDefines_SEEK_1SET
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_UnistdTest_NativeDefines
 * Method:    STDERR_FILENO
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_UnistdTest_00024NativeDefines_STDERR_1FILENO
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_UnistdTest_NativeDefines
 * Method:    STDIN_FILENO
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_UnistdTest_00024NativeDefines_STDIN_1FILENO
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_UnistdTest_NativeDefines
 * Method:    STDOUT_FILENO
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_UnistdTest_00024NativeDefines_STDOUT_1FILENO
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
