/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_PollTest_NativeDefines */

#ifndef _Included_de_ibapl_jnhw_posix_PollTest_NativeDefines
#define _Included_de_ibapl_jnhw_posix_PollTest_NativeDefines
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_PollTest_NativeDefines
 * Method:    HAVE_POLL_H
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_posix_PollTest_00024NativeDefines_HAVE_1POLL_1H
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_PollTest_NativeDefines
 * Method:    POLLERR
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_de_ibapl_jnhw_posix_PollTest_00024NativeDefines_POLLERR
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_PollTest_NativeDefines
 * Method:    POLLHUP
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_de_ibapl_jnhw_posix_PollTest_00024NativeDefines_POLLHUP
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_PollTest_NativeDefines
 * Method:    POLLIN
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_de_ibapl_jnhw_posix_PollTest_00024NativeDefines_POLLIN
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_PollTest_NativeDefines
 * Method:    POLLNVAL
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_de_ibapl_jnhw_posix_PollTest_00024NativeDefines_POLLNVAL
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_PollTest_NativeDefines
 * Method:    POLLOUT
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_de_ibapl_jnhw_posix_PollTest_00024NativeDefines_POLLOUT
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_PollTest_NativeDefines
 * Method:    POLLPRI
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_de_ibapl_jnhw_posix_PollTest_00024NativeDefines_POLLPRI
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_PollTest_NativeDefines
 * Method:    POLLRDBAND
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_de_ibapl_jnhw_posix_PollTest_00024NativeDefines_POLLRDBAND
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_PollTest_NativeDefines
 * Method:    POLLRDNORM
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_de_ibapl_jnhw_posix_PollTest_00024NativeDefines_POLLRDNORM
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_PollTest_NativeDefines
 * Method:    POLLWRBAND
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_de_ibapl_jnhw_posix_PollTest_00024NativeDefines_POLLWRBAND
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_PollTest_NativeDefines
 * Method:    POLLWRNORM
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_de_ibapl_jnhw_posix_PollTest_00024NativeDefines_POLLWRNORM
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
