/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_FcntlTest_NativeDefines */

#ifndef _Included_de_ibapl_jnhw_posix_FcntlTest_NativeDefines
#define _Included_de_ibapl_jnhw_posix_FcntlTest_NativeDefines
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    HAVE_FCNTL_H
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_HAVE_1FCNTL_1H
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    AT_EACCESS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_AT_1EACCESS
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    AT_FDCWD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_AT_1FDCWD
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    AT_REMOVEDIR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_AT_1REMOVEDIR
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    AT_SYMLINK_FOLLOW
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_AT_1SYMLINK_1FOLLOW
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    AT_SYMLINK_NOFOLLOW
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_AT_1SYMLINK_1NOFOLLOW
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    FD_CLOEXEC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_FD_1CLOEXEC
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    F_DUPFD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_F_1DUPFD
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    F_DUPFD_CLOEXEC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_F_1DUPFD_1CLOEXEC
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    F_GETFD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_F_1GETFD
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    F_GETFL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_F_1GETFL
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    F_GETLK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_F_1GETLK
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    F_GETOWN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_F_1GETOWN
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    F_RDLCK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_F_1RDLCK
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    F_SETFD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_F_1SETFD
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    F_SETFL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_F_1SETFL
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    F_SETLK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_F_1SETLK
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    F_SETLKW
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_F_1SETLKW
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    F_SETOWN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_F_1SETOWN
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    F_UNLCK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_F_1UNLCK
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    F_WRLCK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_F_1WRLCK
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    O_ACCMODE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_O_1ACCMODE
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    O_APPEND
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_O_1APPEND
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    O_ASYNC
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_O_1ASYNC
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    O_CLOEXEC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_O_1CLOEXEC
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    O_CREAT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_O_1CREAT
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    O_DIRECTORY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_O_1DIRECTORY
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    O_DSYNC
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_O_1DSYNC
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    O_EXCL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_O_1EXCL
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    O_EXEC
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_O_1EXEC
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    O_FSYNC
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_O_1FSYNC
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    O_LARGEFILE
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_O_1LARGEFILE
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    O_NOCTTY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_O_1NOCTTY
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    O_NOFOLLOW
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_O_1NOFOLLOW
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    O_NONBLOCK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_O_1NONBLOCK
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    O_RDONLY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_O_1RDONLY
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    O_RDWR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_O_1RDWR
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    O_RSYNC
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_O_1RSYNC
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    O_SEARCH
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_O_1SEARCH
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    O_SYNC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_O_1SYNC
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    O_TRUNC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_O_1TRUNC
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    O_TTY_INIT
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_O_1TTY_1INIT
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    O_WRONLY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_O_1WRONLY
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    POSIX_FADV_DONTNEED
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_POSIX_1FADV_1DONTNEED
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    POSIX_FADV_NOREUSE
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_POSIX_1FADV_1NOREUSE
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    POSIX_FADV_NORMAL
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_POSIX_1FADV_1NORMAL
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    POSIX_FADV_RANDOM
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_POSIX_1FADV_1RANDOM
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    POSIX_FADV_SEQUENTIAL
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_POSIX_1FADV_1SEQUENTIAL
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    POSIX_FADV_WILLNEED
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_POSIX_1FADV_1WILLNEED
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    SEEK_CUR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_SEEK_1CUR
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    SEEK_END
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_SEEK_1END
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_FcntlTest_NativeDefines
 * Method:    SEEK_SET
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_FcntlTest_00024NativeDefines_SEEK_1SET
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
