/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_LocaleTest_NativeLconv_t */

#ifndef _Included_de_ibapl_jnhw_posix_LocaleTest_NativeLconv_t
#define _Included_de_ibapl_jnhw_posix_LocaleTest_NativeLconv_t
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_LocaleTest_NativeLconv_t
 * Method:    alignof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_LocaleTest_00024NativeLconv_1t_alignof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_LocaleTest_NativeLconv_t
 * Method:    sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_LocaleTest_00024NativeLconv_1t_sizeof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_LocaleTest_NativeLconv_t
 * Method:    currency_symbol
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_LocaleTest_00024NativeLconv_1t_currency_1symbol
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_LocaleTest_NativeLconv_t
 * Method:    decimal_point
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_LocaleTest_00024NativeLconv_1t_decimal_1point
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_LocaleTest_NativeLconv_t
 * Method:    frac_digits
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_LocaleTest_00024NativeLconv_1t_frac_1digits
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_LocaleTest_NativeLconv_t
 * Method:    grouping
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_LocaleTest_00024NativeLconv_1t_grouping
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_LocaleTest_NativeLconv_t
 * Method:    int_curr_symbol
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_LocaleTest_00024NativeLconv_1t_int_1curr_1symbol
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_LocaleTest_NativeLconv_t
 * Method:    int_frac_digits
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_LocaleTest_00024NativeLconv_1t_int_1frac_1digits
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_LocaleTest_NativeLconv_t
 * Method:    int_n_cs_precedes
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_LocaleTest_00024NativeLconv_1t_int_1n_1cs_1precedes
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_LocaleTest_NativeLconv_t
 * Method:    int_n_sep_by_space
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_LocaleTest_00024NativeLconv_1t_int_1n_1sep_1by_1space
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_LocaleTest_NativeLconv_t
 * Method:    int_n_sign_posn
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_LocaleTest_00024NativeLconv_1t_int_1n_1sign_1posn
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_LocaleTest_NativeLconv_t
 * Method:    int_p_cs_precedes
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_LocaleTest_00024NativeLconv_1t_int_1p_1cs_1precedes
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_LocaleTest_NativeLconv_t
 * Method:    int_p_sep_by_space
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_LocaleTest_00024NativeLconv_1t_int_1p_1sep_1by_1space
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_LocaleTest_NativeLconv_t
 * Method:    int_p_sign_posn
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_LocaleTest_00024NativeLconv_1t_int_1p_1sign_1posn
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_LocaleTest_NativeLconv_t
 * Method:    mon_decimal_point
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_LocaleTest_00024NativeLconv_1t_mon_1decimal_1point
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_LocaleTest_NativeLconv_t
 * Method:    mon_grouping
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_LocaleTest_00024NativeLconv_1t_mon_1grouping
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_LocaleTest_NativeLconv_t
 * Method:    mon_thousands_sep
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_LocaleTest_00024NativeLconv_1t_mon_1thousands_1sep
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_LocaleTest_NativeLconv_t
 * Method:    negative_sign
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_LocaleTest_00024NativeLconv_1t_negative_1sign
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_LocaleTest_NativeLconv_t
 * Method:    n_cs_precedes
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_LocaleTest_00024NativeLconv_1t_n_1cs_1precedes
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_LocaleTest_NativeLconv_t
 * Method:    n_sep_by_space
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_LocaleTest_00024NativeLconv_1t_n_1sep_1by_1space
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_LocaleTest_NativeLconv_t
 * Method:    n_sign_posn
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_LocaleTest_00024NativeLconv_1t_n_1sign_1posn
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_LocaleTest_NativeLconv_t
 * Method:    positive_sign
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_LocaleTest_00024NativeLconv_1t_positive_1sign
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_LocaleTest_NativeLconv_t
 * Method:    p_cs_precedes
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_LocaleTest_00024NativeLconv_1t_p_1cs_1precedes
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_LocaleTest_NativeLconv_t
 * Method:    p_sep_by_space
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_LocaleTest_00024NativeLconv_1t_p_1sep_1by_1space
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_LocaleTest_NativeLconv_t
 * Method:    p_sign_posn
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_LocaleTest_00024NativeLconv_1t_p_1sign_1posn
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_LocaleTest_NativeLconv_t
 * Method:    thousands_sep
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_LocaleTest_00024NativeLconv_1t_thousands_1sep
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
