/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_PollTest_NativePollFd */

#ifndef _Included_de_ibapl_jnhw_posix_PollTest_NativePollFd
#define _Included_de_ibapl_jnhw_posix_PollTest_NativePollFd
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_PollTest_NativePollFd
 * Method:    alignof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_PollTest_00024NativePollFd_alignof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_PollTest_NativePollFd
 * Method:    sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_PollTest_00024NativePollFd_sizeof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_PollTest_NativePollFd
 * Method:    fd
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_PollTest_00024NativePollFd_fd
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_PollTest_NativePollFd
 * Method:    events
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_PollTest_00024NativePollFd_events
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_PollTest_NativePollFd
 * Method:    revents
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_PollTest_00024NativePollFd_revents
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
