/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_linux_sys_EventfdTest_NativeDefines */

#ifndef _Included_de_ibapl_jnhw_linux_sys_EventfdTest_NativeDefines
#define _Included_de_ibapl_jnhw_linux_sys_EventfdTest_NativeDefines
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_linux_sys_EventfdTest_NativeDefines
 * Method:    HAVE_SYS_EVENTFD_H
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_linux_sys_EventfdTest_00024NativeDefines_HAVE_1SYS_1EVENTFD_1H
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_linux_sys_EventfdTest_NativeDefines
 * Method:    EFD_CLOEXEC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_linux_sys_EventfdTest_00024NativeDefines_EFD_1CLOEXEC
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_linux_sys_EventfdTest_NativeDefines
 * Method:    EFD_NONBLOCK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_linux_sys_EventfdTest_00024NativeDefines_EFD_1NONBLOCK
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_linux_sys_EventfdTest_NativeDefines
 * Method:    EFD_SEMAPHORE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_linux_sys_EventfdTest_00024NativeDefines_EFD_1SEMAPHORE
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
