/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_TermiosTest_NativeStructTermios */

#ifndef _Included_de_ibapl_jnhw_posix_TermiosTest_NativeStructTermios
#define _Included_de_ibapl_jnhw_posix_TermiosTest_NativeStructTermios
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeStructTermios
 * Method:    alignof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeStructTermios_alignof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeStructTermios
 * Method:    sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeStructTermios_sizeof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeStructTermios
 * Method:    c_iflag
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeStructTermios_c_1iflag
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeStructTermios
 * Method:    c_oflag
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeStructTermios_c_1oflag
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeStructTermios
 * Method:    c_cflag
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeStructTermios_c_1cflag
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeStructTermios
 * Method:    c_lflag
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeStructTermios_c_1lflag
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeStructTermios
 * Method:    c_cc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeStructTermios_c_1cc
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeStructTermios
 * Method:    c_line
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeStructTermios_c_1line
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeStructTermios
 * Method:    c_ispeed
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeStructTermios_c_1ispeed
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_TermiosTest_NativeStructTermios
 * Method:    c_ospeed
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_TermiosTest_00024NativeStructTermios_c_1ospeed
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
