/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_Signal_Stack_t */

#ifndef _Included_de_ibapl_jnhw_posix_Signal_Stack_t
#define _Included_de_ibapl_jnhw_posix_Signal_Stack_t
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_Signal_Stack_t
 * Method:    sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Signal_00024Stack_1t_sizeof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Signal_Stack_t
 * Method:    alignof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Signal_00024Stack_1t_alignof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Signal_Stack_t
 * Method:    ss_flags
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_00024Stack_1t_ss_1flags__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Signal_Stack_t
 * Method:    ss_sp0
 * Signature: ()Lde/ibapl/jnhw/common/memory/NativeAddressHolder;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_Signal_00024Stack_1t_ss_1sp0
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Signal_Stack_t
 * Method:    ss_size
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_00024Stack_1t_ss_1size__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_Signal_Stack_t
 * Method:    ss_size
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_Signal_00024Stack_1t_ss_1size__
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Signal_Stack_t
 * Method:    ss_flags
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Signal_00024Stack_1t_ss_1flags__
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Signal_Stack_t
 * Method:    ss_sp
 * Signature: (Lde/ibapl/jnhw/common/memory/OpaqueMemory32;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_00024Stack_1t_ss_1sp
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
