/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_Poll */

#ifndef _Included_de_ibapl_jnhw_posix_Poll
#define _Included_de_ibapl_jnhw_posix_Poll
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_Poll
 * Method:    poll
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Poll_poll
  (JNIEnv *, jclass, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
