/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_x_open_Ucontext */

#ifndef _Included_de_ibapl_jnhw_x_open_Ucontext
#define _Included_de_ibapl_jnhw_x_open_Ucontext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_x_open_Ucontext
 * Method:    getcontext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_x_1open_Ucontext_getcontext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_ibapl_jnhw_x_open_Ucontext
 * Method:    setcontext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_x_1open_Ucontext_setcontext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_ibapl_jnhw_x_open_Ucontext
 * Method:    swapcontext
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_x_1open_Ucontext_swapcontext
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
