/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_util_posix_Defines */

#ifndef _Included_de_ibapl_jnhw_util_posix_Defines
#define _Included_de_ibapl_jnhw_util_posix_Defines
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_util_posix_Defines
 * Method:    initFields
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_util_posix_Defines_initFields
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
