/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_Time_Itimerspec */

#ifndef _Included_de_ibapl_jnhw_posix_Time_Itimerspec
#define _Included_de_ibapl_jnhw_posix_Time_Itimerspec
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_Time_Itimerspec
 * Method:    sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Time_00024Itimerspec_sizeof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Time_Itimerspec
 * Method:    alignof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Time_00024Itimerspec_alignof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Time_Itimerspec
 * Method:    offsetof_It_interval
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Time_00024Itimerspec_offsetof_1It_1interval
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Time_Itimerspec
 * Method:    offsetof_It_value
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Time_00024Itimerspec_offsetof_1It_1value
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
