/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_Pthread */

#ifndef _Included_de_ibapl_jnhw_posix_Pthread
#define _Included_de_ibapl_jnhw_posix_Pthread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_Pthread
 * Method:    initFields
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Pthread_initFields
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Pthread
 * Method:    pthread_self0
 * Signature: (Lde/ibapl/jnhw/posix/Pthread/Pthread_t;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Pthread_pthread_1self0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Pthread
 * Method:    pthread_equal
 * Signature: (Lde/ibapl/jnhw/posix/Pthread/Pthread_t;Lde/ibapl/jnhw/posix/Pthread/Pthread_t;)Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_posix_Pthread_pthread_1equal
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Pthread
 * Method:    pthread_attr_getinheritsched
 * Signature: (Lde/ibapl/jnhw/posix/Pthread/Pthread_attr_t;)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Pthread_pthread_1attr_1getinheritsched
  (JNIEnv *, jclass, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Pthread
 * Method:    pthread_attr_getschedparam
 * Signature: (Lde/ibapl/jnhw/posix/Pthread/Pthread_attr_t;Lde/ibapl/jnhw/posix/Sched/Sched_param;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Pthread_pthread_1attr_1getschedparam
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Pthread
 * Method:    pthread_attr_setinheritsched
 * Signature: (Lde/ibapl/jnhw/posix/Pthread/Pthread_attr_t;I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Pthread_pthread_1attr_1setinheritsched
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Pthread
 * Method:    pthread_attr_setschedparam
 * Signature: (Lde/ibapl/jnhw/posix/Pthread/Pthread_attr_t;Lde/ibapl/jnhw/posix/Sched/Sched_param;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Pthread_pthread_1attr_1setschedparam
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Pthread
 * Method:    pthread_getschedparam
 * Signature: (Lde/ibapl/jnhw/posix/Pthread/Pthread_t;Lde/ibapl/jnhw/common/references/IntRef;Lde/ibapl/jnhw/posix/Sched/Sched_param;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Pthread_pthread_1getschedparam
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Pthread
 * Method:    pthread_setschedparam
 * Signature: (Lde/ibapl/jnhw/posix/Pthread/Pthread_t;ILde/ibapl/jnhw/posix/Sched/Sched_param;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Pthread_pthread_1setschedparam
  (JNIEnv *, jclass, jobject, jint, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Pthread
 * Method:    pthread_setschedprio
 * Signature: (Lde/ibapl/jnhw/posix/Pthread/Pthread_t;I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Pthread_pthread_1setschedprio
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Pthread
 * Method:    pthread_getcpuclockid
 * Signature: (Lde/ibapl/jnhw/posix/Pthread/Pthread_t;Lde/ibapl/jnhw/common/references/IntRef;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Pthread_pthread_1getcpuclockid
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Pthread
 * Method:    pthread_attr_destroy
 * Signature: (Lde/ibapl/jnhw/posix/Pthread/Pthread_attr_t;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Pthread_pthread_1attr_1destroy
  (JNIEnv *, jclass, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Pthread
 * Method:    pthread_attr_init
 * Signature: (Lde/ibapl/jnhw/posix/Pthread/Pthread_attr_t;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Pthread_pthread_1attr_1init
  (JNIEnv *, jclass, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Pthread
 * Method:    pthread_cancel
 * Signature: (Lde/ibapl/jnhw/posix/Pthread/Pthread_t;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Pthread_pthread_1cancel
  (JNIEnv *, jclass, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Pthread
 * Method:    pthread_testcancel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Pthread_pthread_1testcancel
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Pthread
 * Method:    pthread_setcancelstate
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Pthread_pthread_1setcancelstate
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Pthread
 * Method:    pthread_setcanceltype
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Pthread_pthread_1setcanceltype
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
