/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_isoc_Errno */

#ifndef _Included_de_ibapl_jnhw_isoc_Errno
#define _Included_de_ibapl_jnhw_isoc_Errno
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_isoc_Errno
 * Method:    initFields
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_isoc_Errno_initFields
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_isoc_Errno
 * Method:    errno
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_isoc_Errno_errno__
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_isoc_Errno
 * Method:    errno
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_isoc_Errno_errno__I
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
