/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_Time_Itimerspec */

#ifndef _Included_de_ibapl_jnhw_posix_Time_Itimerspec
#define _Included_de_ibapl_jnhw_posix_Time_Itimerspec
#ifdef __cplusplus
extern "C" {
#endif
#undef de_ibapl_jnhw_posix_Time_Itimerspec_NULL
#define de_ibapl_jnhw_posix_Time_Itimerspec_NULL 0LL
/*
 * Class:     de_ibapl_jnhw_posix_Time_Itimerspec
 * Method:    native2Layout
 * Signature: (Ljava/lang/Class;)Lde/ibapl/jnhw/posix/Time/Itimerspec/Layout;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_Time_00024Itimerspec_native2Layout
  (JNIEnv *, jclass, jclass);

#ifdef __cplusplus
}
#endif
#endif
