/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_Aio */

#ifndef _Included_de_ibapl_jnhw_posix_Aio
#define _Included_de_ibapl_jnhw_posix_Aio
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_Aio
 * Method:    aio_cancel
 * Signature: (IJ)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Aio_aio_1cancel
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_Aio
 * Method:    aio_error
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Aio_aio_1error
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_Aio
 * Method:    aio_fsync
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Aio_aio_1fsync
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_Aio
 * Method:    aio_read
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Aio_aio_1read
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_Aio
 * Method:    aio_return
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_Aio_aio_1return
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_Aio
 * Method:    aio_suspend
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Aio_aio_1suspend
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_Aio
 * Method:    aio_write
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Aio_aio_1write
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_Aio
 * Method:    lio_listio
 * Signature: (IJIJ)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Aio_lio_1listio
  (JNIEnv *, jclass, jint, jlong, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
