/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_Termios */

#ifndef _Included_de_ibapl_jnhw_posix_Termios
#define _Included_de_ibapl_jnhw_posix_Termios
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_Termios
 * Method:    initFields
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Termios_initFields
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Termios
 * Method:    cfgetispeed
 * Signature: (Lde/ibapl/jnhw/posix/Termios/StructTermios;)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Termios_cfgetispeed
  (JNIEnv *, jclass, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Termios
 * Method:    cfgetospeed
 * Signature: (Lde/ibapl/jnhw/posix/Termios/StructTermios;)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Termios_cfgetospeed
  (JNIEnv *, jclass, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Termios
 * Method:    cfsetispeed
 * Signature: (Lde/ibapl/jnhw/posix/Termios/StructTermios;I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Termios_cfsetispeed
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Termios
 * Method:    cfsetospeed
 * Signature: (Lde/ibapl/jnhw/posix/Termios/StructTermios;I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Termios_cfsetospeed
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Termios
 * Method:    cfsetspeed
 * Signature: (Lde/ibapl/jnhw/posix/Termios/StructTermios;I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Termios_cfsetspeed
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Termios
 * Method:    tcdrain
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Termios_tcdrain
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Termios
 * Method:    tcflow
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Termios_tcflow
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Termios
 * Method:    tcflush
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Termios_tcflush
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Termios
 * Method:    tcgetattr
 * Signature: (ILde/ibapl/jnhw/posix/Termios/StructTermios;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Termios_tcgetattr
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Termios
 * Method:    tcgetsid
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Termios_tcgetsid
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Termios
 * Method:    tcsendbreak
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Termios_tcsendbreak
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Termios
 * Method:    tcsetattr
 * Signature: (IILde/ibapl/jnhw/posix/Termios/StructTermios;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Termios_tcsetattr
  (JNIEnv *, jclass, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
