/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_Poll */

#ifndef _Included_de_ibapl_jnhw_posix_Poll
#define _Included_de_ibapl_jnhw_posix_Poll
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_Poll
 * Method:    initFields
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Poll_initFields
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Poll
 * Method:    poll
 * Signature: (Lde/ibapl/jnhw/posix/Poll/PollFds;I)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Poll_poll__Lde_ibapl_jnhw_posix_Poll_PollFds_2I
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Poll
 * Method:    poll
 * Signature: (Lde/ibapl/jnhw/posix/Poll/PollFd;I)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Poll_poll__Lde_ibapl_jnhw_posix_Poll_PollFd_2I
  (JNIEnv *, jclass, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
