/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_util_posix_PosixDataType */

#ifndef _Included_de_ibapl_jnhw_util_posix_PosixDataType
#define _Included_de_ibapl_jnhw_util_posix_PosixDataType
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_util_posix_PosixDataType
 * Method:    JNHW__cc_t__IS__uint8_t
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_util_posix_PosixDataType_JNHW_1_1cc_1t_1_1IS_1_1uint8_1t
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_PosixDataType
 * Method:    JNHW__clock_t__IS__int64_t
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_util_posix_PosixDataType_JNHW_1_1clock_1t_1_1IS_1_1int64_1t
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_PosixDataType
 * Method:    JNHW__clock_t__IS__int32_t
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_util_posix_PosixDataType_JNHW_1_1clock_1t_1_1IS_1_1int32_1t
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_PosixDataType
 * Method:    JNHW__off_t__IS__int64_t
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_util_posix_PosixDataType_JNHW_1_1off_1t_1_1IS_1_1int64_1t
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_PosixDataType
 * Method:    JNHW__off_t__IS__int32_t
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_util_posix_PosixDataType_JNHW_1_1off_1t_1_1IS_1_1int32_1t
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_PosixDataType
 * Method:    JNHW__mode_t__IS__uint16_t
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_util_posix_PosixDataType_JNHW_1_1mode_1t_1_1IS_1_1uint16_1t
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_PosixDataType
 * Method:    JNHW__mode_t__IS__uint32_t
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_util_posix_PosixDataType_JNHW_1_1mode_1t_1_1IS_1_1uint32_1t
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_PosixDataType
 * Method:    JNHW__pid_t__IS__int32_t
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_util_posix_PosixDataType_JNHW_1_1pid_1t_1_1IS_1_1int32_1t
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_PosixDataType
 * Method:    JNHW__speed_t__IS__uint32_t
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_util_posix_PosixDataType_JNHW_1_1speed_1t_1_1IS_1_1uint32_1t
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_PosixDataType
 * Method:    JNHW__size_t__IS__uint64_t
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_util_posix_PosixDataType_JNHW_1_1size_1t_1_1IS_1_1uint64_1t
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_PosixDataType
 * Method:    JNHW__size_t__IS__uint32_t
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_util_posix_PosixDataType_JNHW_1_1size_1t_1_1IS_1_1uint32_1t
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_PosixDataType
 * Method:    JNHW__ssize_t__IS__int64_t
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_util_posix_PosixDataType_JNHW_1_1ssize_1t_1_1IS_1_1int64_1t
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_PosixDataType
 * Method:    JNHW__ssize_t__IS__int32_t
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_util_posix_PosixDataType_JNHW_1_1ssize_1t_1_1IS_1_1int32_1t
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_PosixDataType
 * Method:    JNHW__tcflag_t__IS__uint32_t
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_util_posix_PosixDataType_JNHW_1_1tcflag_1t_1_1IS_1_1uint32_1t
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_PosixDataType
 * Method:    JNHW__time_t__IS__int64_t
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_util_posix_PosixDataType_JNHW_1_1time_1t_1_1IS_1_1int64_1t
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_PosixDataType
 * Method:    JNHW__time_t__IS__int32_t
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_util_posix_PosixDataType_JNHW_1_1time_1t_1_1IS_1_1int32_1t
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_PosixDataType
 * Method:    JNHW__uid_t__IS__uint32_t
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_util_posix_PosixDataType_JNHW_1_1uid_1t_1_1IS_1_1uint32_1t
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
