/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_Aio_Aiocb */

#ifndef _Included_de_ibapl_jnhw_posix_Aio_Aiocb
#define _Included_de_ibapl_jnhw_posix_Aio_Aiocb
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_Aio_Aiocb
 * Method:    native2Layout
 * Signature: (Ljava/lang/Class;)Lde/ibapl/jnhw/posix/Aio/Aiocb/Layout;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_Aio_00024Aiocb_native2Layout
  (JNIEnv *, jclass, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Aio_Aiocb
 * Method:    aio_bufByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Aio_00024Aiocb_aio_1bufByteBuffer
  (JNIEnv *, jobject, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
