/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_Signal_Sigaction */

#ifndef _Included_de_ibapl_jnhw_posix_Signal_Sigaction
#define _Included_de_ibapl_jnhw_posix_Signal_Sigaction
#ifdef __cplusplus
extern "C" {
#endif
#undef de_ibapl_jnhw_posix_Signal_Sigaction_NULL
#define de_ibapl_jnhw_posix_Signal_Sigaction_NULL 0LL
/*
 * Class:     de_ibapl_jnhw_posix_Signal_Sigaction
 * Method:    native2Layout
 * Signature: (Ljava/lang/Class;)Lde/ibapl/jnhw/posix/Signal/Sigaction/Layout;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_Signal_00024Sigaction_native2Layout
  (JNIEnv *, jclass, jclass);

#ifdef __cplusplus
}
#endif
#endif
