/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_Time */

#ifndef _Included_de_ibapl_jnhw_posix_Time
#define _Included_de_ibapl_jnhw_posix_Time
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_Time
 * Method:    initFields
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Time_initFields
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Time
 * Method:    asctime
 * Signature: (Lde/ibapl/jnhw/posix/Time/Tm;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_ibapl_jnhw_posix_Time_asctime
  (JNIEnv *, jclass, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Time
 * Method:    asctime_r
 * Signature: (Lde/ibapl/jnhw/posix/Time/Tm;Lde/ibapl/jnhw/common/memory/OpaqueMemory32;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_ibapl_jnhw_posix_Time_asctime_1r
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Time
 * Method:    clock
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_Time_clock
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Time
 * Method:    clock_getcpuclockid
 * Signature: (ILde/ibapl/jnhw/common/references/IntRef;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Time_clock_1getcpuclockid
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Time
 * Method:    clock_getres
 * Signature: (ILde/ibapl/jnhw/posix/Time/Timespec;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Time_clock_1getres
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Time
 * Method:    clock_gettime
 * Signature: (ILde/ibapl/jnhw/posix/Time/Timespec;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Time_clock_1gettime
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Time
 * Method:    clock_nanosleep
 * Signature: (IILde/ibapl/jnhw/posix/Time/Timespec;Lde/ibapl/jnhw/posix/Time/Timespec;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Time_clock_1nanosleep
  (JNIEnv *, jclass, jint, jint, jobject, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Time
 * Method:    clock_settime
 * Signature: (ILde/ibapl/jnhw/posix/Time/Timespec;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Time_clock_1settime
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Time
 * Method:    ctime
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_ibapl_jnhw_posix_Time_ctime
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_Time
 * Method:    ctime_r
 * Signature: (JLde/ibapl/jnhw/common/memory/OpaqueMemory32;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_ibapl_jnhw_posix_Time_ctime_1r
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Time
 * Method:    daylight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Time_daylight
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Time
 * Method:    difftime
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_de_ibapl_jnhw_posix_Time_difftime
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_Time
 * Method:    getdate0
 * Signature: (Ljava/lang/String;)Lde/ibapl/jnhw/common/memory/NativeAddressHolder;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_Time_getdate0
  (JNIEnv *, jclass, jstring);

/*
 * Class:     de_ibapl_jnhw_posix_Time
 * Method:    gmtime0
 * Signature: (J)Lde/ibapl/jnhw/common/memory/NativeAddressHolder;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_Time_gmtime0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_Time
 * Method:    gmtime_r
 * Signature: (JLde/ibapl/jnhw/posix/Time/Tm;)Lde/ibapl/jnhw/posix/Time/Tm;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_Time_gmtime_1r
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Time
 * Method:    localtime0
 * Signature: (J)Lde/ibapl/jnhw/common/memory/NativeAddressHolder;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_Time_localtime0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_Time
 * Method:    localtime_r
 * Signature: (JLde/ibapl/jnhw/posix/Time/Tm;)Lde/ibapl/jnhw/posix/Time/Tm;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_Time_localtime_1r
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Time
 * Method:    mktime
 * Signature: (Lde/ibapl/jnhw/posix/Time/Tm;)J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_Time_mktime
  (JNIEnv *, jclass, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Time
 * Method:    nanosleep
 * Signature: (Lde/ibapl/jnhw/posix/Time/Timespec;Lde/ibapl/jnhw/posix/Time/Timespec;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Time_nanosleep
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Time
 * Method:    strftime
 * Signature: (JLjava/lang/String;Lde/ibapl/jnhw/posix/Time/Tm;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_ibapl_jnhw_posix_Time_strftime
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Time
 * Method:    strftime_l
 * Signature: (JLjava/lang/String;Lde/ibapl/jnhw/posix/Time/Tm;Lde/ibapl/jnhw/posix/Locale/Locale_t;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_ibapl_jnhw_posix_Time_strftime_1l
  (JNIEnv *, jclass, jlong, jstring, jobject, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Time
 * Method:    strptime
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lde/ibapl/jnhw/posix/Time/Tm;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_ibapl_jnhw_posix_Time_strptime
  (JNIEnv *, jclass, jstring, jstring, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Time
 * Method:    time
 * Signature: (Lde/ibapl/jnhw/common/references/LongRef;)J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_Time_time
  (JNIEnv *, jclass, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Time
 * Method:    timer_create
 * Signature: (ILde/ibapl/jnhw/posix/Signal/Sigevent;Lde/ibapl/jnhw/posix/Time/Timer_t;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Time_timer_1create
  (JNIEnv *, jclass, jint, jobject, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Time
 * Method:    timer_delete
 * Signature: (Lde/ibapl/jnhw/posix/Time/Timer_t;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Time_timer_1delete
  (JNIEnv *, jclass, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Time
 * Method:    timer_getoverrun
 * Signature: (Lde/ibapl/jnhw/posix/Time/Timer_t;)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Time_timer_1getoverrun
  (JNIEnv *, jclass, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Time
 * Method:    timer_gettime
 * Signature: (Lde/ibapl/jnhw/posix/Time/Timer_t;Lde/ibapl/jnhw/posix/Time/Itimerspec;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Time_timer_1gettime
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Time
 * Method:    timer_settime
 * Signature: (Lde/ibapl/jnhw/posix/Time/Timer_t;ILde/ibapl/jnhw/posix/Time/Itimerspec;Lde/ibapl/jnhw/posix/Time/Itimerspec;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Time_timer_1settime
  (JNIEnv *, jclass, jobject, jint, jobject, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Time
 * Method:    timezone
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_Time_timezone
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Time
 * Method:    tzname
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_de_ibapl_jnhw_posix_Time_tzname
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Time
 * Method:    tzset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Time_tzset
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
