/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_Locale */

#ifndef _Included_de_ibapl_jnhw_posix_Locale
#define _Included_de_ibapl_jnhw_posix_Locale
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_Locale
 * Method:    initFields
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Locale_initFields
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Locale
 * Method:    duplocale
 * Signature: (Lde/ibapl/jnhw/posix/Locale/Locale_t;)Lde/ibapl/jnhw/posix/Locale/Locale_t;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_Locale_duplocale
  (JNIEnv *, jclass, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Locale
 * Method:    freelocale
 * Signature: (Lde/ibapl/jnhw/posix/Locale/Locale_t;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Locale_freelocale
  (JNIEnv *, jclass, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Locale
 * Method:    localeconv
 * Signature: ()Lde/ibapl/jnhw/posix/Locale/Lconv;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_Locale_localeconv
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Locale
 * Method:    newlocale
 * Signature: (ILjava/lang/String;Lde/ibapl/jnhw/posix/Locale/Locale_t;)Lde/ibapl/jnhw/posix/Locale/Locale_t;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_Locale_newlocale
  (JNIEnv *, jclass, jint, jstring, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Locale
 * Method:    setlocale
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_ibapl_jnhw_posix_Locale_setlocale
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     de_ibapl_jnhw_posix_Locale
 * Method:    uselocale
 * Signature: (Lde/ibapl/jnhw/posix/Locale/Locale_t;)Lde/ibapl/jnhw/posix/Locale/Locale_t;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_Locale_uselocale
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
