/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_sys_Types_Clock_t */

#ifndef _Included_de_ibapl_jnhw_posix_sys_Types_Clock_t
#define _Included_de_ibapl_jnhw_posix_sys_Types_Clock_t
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_sys_Types_Clock_t
 * Method:    sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_sys_Types_00024Clock_1t_sizeof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_sys_Types_Clock_t
 * Method:    alignof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_sys_Types_00024Clock_1t_alignof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_sys_Types_Clock_t
 * Method:    unsigned
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_posix_sys_Types_00024Clock_1t_unsigned
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_sys_Types_Clock_t
 * Method:    getValue
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_sys_Types_00024Clock_1t_getValue
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_sys_Types_Clock_t
 * Method:    setValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_sys_Types_00024Clock_1t_setValue
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_sys_Types_Clock_t
 * Method:    nativeToString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_ibapl_jnhw_posix_sys_Types_00024Clock_1t_nativeToString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
