/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_Sched_Sched_param */

#ifndef _Included_de_ibapl_jnhw_posix_Sched_Sched_param
#define _Included_de_ibapl_jnhw_posix_Sched_Sched_param
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_Sched_Sched_param
 * Method:    sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Sched_00024Sched_1param_sizeof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Sched_Sched_param
 * Method:    alignof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Sched_00024Sched_1param_alignof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Sched_Sched_param
 * Method:    offsetof_Sched_ss_init_budget
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Sched_00024Sched_1param_offsetof_1Sched_1ss_1init_1budget
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Sched_Sched_param
 * Method:    offsetof_Sched_ss_repl_period
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Sched_00024Sched_1param_offsetof_1Sched_1ss_1repl_1period
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Sched_Sched_param
 * Method:    sched_priority
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Sched_00024Sched_1param_sched_1priority__
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Sched_Sched_param
 * Method:    sched_priority
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Sched_00024Sched_1param_sched_1priority__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Sched_Sched_param
 * Method:    sched_ss_low_priority
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Sched_00024Sched_1param_sched_1ss_1low_1priority__
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Sched_Sched_param
 * Method:    sched_ss_low_priority
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Sched_00024Sched_1param_sched_1ss_1low_1priority__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Sched_Sched_param
 * Method:    sched_ss_max_repl
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Sched_00024Sched_1param_sched_1ss_1max_1repl__
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Sched_Sched_param
 * Method:    sched_ss_max_repl
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Sched_00024Sched_1param_sched_1ss_1max_1repl__I
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
