/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_Locale_Lconv */

#ifndef _Included_de_ibapl_jnhw_posix_Locale_Lconv
#define _Included_de_ibapl_jnhw_posix_Locale_Lconv
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_Locale_Lconv
 * Method:    native2Layout
 * Signature: (Ljava/lang/Class;)Lde/ibapl/jnhw/posix/Locale/Lconv/Layout;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_Locale_00024Lconv_native2Layout
  (JNIEnv *, jclass, jclass);

#ifdef __cplusplus
}
#endif
#endif
