/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_Stdio */

#ifndef _Included_de_ibapl_jnhw_posix_Stdio
#define _Included_de_ibapl_jnhw_posix_Stdio
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_Stdio
 * Method:    getchar
 * Signature: ()C
 */
JNIEXPORT jchar JNICALL Java_de_ibapl_jnhw_posix_Stdio_getchar
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Stdio
 * Method:    putchar
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Stdio_putchar
  (JNIEnv *, jclass, jchar);

/*
 * Class:     de_ibapl_jnhw_posix_Stdio
 * Method:    remove
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Stdio_remove
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
