/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_Time_Timespec */

#ifndef _Included_de_ibapl_jnhw_posix_Time_Timespec
#define _Included_de_ibapl_jnhw_posix_Time_Timespec
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_Time_Timespec
 * Method:    native2Layout
 * Signature: (Ljava/lang/Class;)Lde/ibapl/jnhw/posix/Time/Timespec/Layout;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_Time_00024Timespec_native2Layout
  (JNIEnv *, jclass, jclass);

#ifdef __cplusplus
}
#endif
#endif
