/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_Unistd */

#ifndef _Included_de_ibapl_jnhw_posix_Unistd
#define _Included_de_ibapl_jnhw_posix_Unistd
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_Unistd
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Unistd_close
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Unistd
 * Method:    fsync
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Unistd_fsync
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Unistd
 * Method:    getgid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Unistd_getgid
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Unistd
 * Method:    getegid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Unistd_getegid
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Unistd
 * Method:    setgid
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Unistd_setgid
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Unistd
 * Method:    setegid
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Unistd_setegid
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Unistd
 * Method:    setregid
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Unistd_setregid
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Unistd
 * Method:    geteuid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Unistd_geteuid
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Unistd
 * Method:    seteuid
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Unistd_seteuid
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Unistd
 * Method:    getpgrp
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Unistd_getpgrp
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Unistd
 * Method:    getpid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Unistd_getpid
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Unistd
 * Method:    getppid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Unistd_getppid
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Unistd
 * Method:    setreuid
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Unistd_setreuid
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Unistd
 * Method:    getuid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Unistd_getuid
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Unistd
 * Method:    setuid
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Unistd_setuid
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Unistd
 * Method:    lseek
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Unistd_lseek__III
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Unistd
 * Method:    lseek
 * Signature: (IJI)J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_Unistd_lseek__IJI
  (JNIEnv *, jclass, jint, jlong, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Unistd
 * Method:    lseek64
 * Signature: (IJI)J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_Unistd_lseek64
  (JNIEnv *, jclass, jint, jlong, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Unistd
 * Method:    pipe
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Unistd_pipe
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_Unistd
 * Method:    read0
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Unistd_read0
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Unistd
 * Method:    read
 * Signature: (IJII)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Unistd_read__IJII
  (JNIEnv *, jclass, jint, jlong, jint, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Unistd
 * Method:    read
 * Signature: (IJJJ)J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_Unistd_read__IJJJ
  (JNIEnv *, jclass, jint, jlong, jlong, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_Unistd
 * Method:    read
 * Signature: (I)S
 */
JNIEXPORT jshort JNICALL Java_de_ibapl_jnhw_posix_Unistd_read__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Unistd
 * Method:    read
 * Signature: (ILjava/nio/ByteBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Unistd_read__ILjava_nio_ByteBuffer_2II
  (JNIEnv *, jclass, jint, jobject, jint, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Unistd
 * Method:    usleep
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Unistd_usleep
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Unistd
 * Method:    write
 * Signature: (IJII)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Unistd_write__IJII
  (JNIEnv *, jclass, jint, jlong, jint, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Unistd
 * Method:    write
 * Signature: (IJJJ)J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_Unistd_write__IJJJ
  (JNIEnv *, jclass, jint, jlong, jlong, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_Unistd
 * Method:    write
 * Signature: (IB)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Unistd_write__IB
  (JNIEnv *, jclass, jint, jbyte);

/*
 * Class:     de_ibapl_jnhw_posix_Unistd
 * Method:    write0
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Unistd_write0
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Unistd
 * Method:    write
 * Signature: (ILjava/nio/ByteBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Unistd_write__ILjava_nio_ByteBuffer_2II
  (JNIEnv *, jclass, jint, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
