/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_Termios_Cc_t */

#ifndef _Included_de_ibapl_jnhw_posix_Termios_Cc_t
#define _Included_de_ibapl_jnhw_posix_Termios_Cc_t
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_Termios_Cc_t
 * Method:    sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Termios_00024Cc_1t_sizeof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Termios_Cc_t
 * Method:    alignof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Termios_00024Cc_1t_alignof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Termios_Cc_t
 * Method:    unsigned
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_posix_Termios_00024Cc_1t_unsigned
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Termios_Cc_t
 * Method:    getValue
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_de_ibapl_jnhw_posix_Termios_00024Cc_1t_getValue
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Termios_Cc_t
 * Method:    setValue
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Termios_00024Cc_1t_setValue
  (JNIEnv *, jobject, jbyte);

#ifdef __cplusplus
}
#endif
#endif
