/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_Termios */

#ifndef _Included_de_ibapl_jnhw_posix_Termios
#define _Included_de_ibapl_jnhw_posix_Termios
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_Termios
 * Method:    cfgetispeed
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_Termios_cfgetispeed
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_Termios
 * Method:    cfgetospeed
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_Termios_cfgetospeed
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_Termios
 * Method:    cfsetispeed
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Termios_cfsetispeed
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_Termios
 * Method:    cfsetospeed
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Termios_cfsetospeed
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_Termios
 * Method:    cfsetspeed
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Termios_cfsetspeed
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_Termios
 * Method:    tcdrain
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Termios_tcdrain
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Termios
 * Method:    tcflow
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Termios_tcflow
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Termios
 * Method:    tcflush
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Termios_tcflush
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Termios
 * Method:    tcgetattr
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Termios_tcgetattr
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_Termios
 * Method:    tcgetsid
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Termios_tcgetsid
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Termios
 * Method:    tcsendbreak
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Termios_tcsendbreak
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Termios
 * Method:    tcsetattr
 * Signature: (IIJ)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Termios_tcsetattr
  (JNIEnv *, jclass, jint, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
