/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_Pthread_Pthread_attr_t */

#ifndef _Included_de_ibapl_jnhw_posix_Pthread_Pthread_attr_t
#define _Included_de_ibapl_jnhw_posix_Pthread_Pthread_attr_t
#ifdef __cplusplus
extern "C" {
#endif
#undef de_ibapl_jnhw_posix_Pthread_Pthread_attr_t_NULL
#define de_ibapl_jnhw_posix_Pthread_Pthread_attr_t_NULL 0LL
/*
 * Class:     de_ibapl_jnhw_posix_Pthread_Pthread_attr_t
 * Method:    native2Layout
 * Signature: (Ljava/lang/Class;)Lde/ibapl/jnhw/posix/Pthread/Pthread_attr_t/Layout;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_Pthread_00024Pthread_1attr_1t_native2Layout
  (JNIEnv *, jclass, jclass);

#ifdef __cplusplus
}
#endif
#endif
