/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_Signal_Ucontext_t */

#ifndef _Included_de_ibapl_jnhw_posix_Signal_Ucontext_t
#define _Included_de_ibapl_jnhw_posix_Signal_Ucontext_t
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_Signal_Ucontext_t
 * Method:    sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Signal_00024Ucontext_1t_sizeof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Signal_Ucontext_t
 * Method:    alignof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Signal_00024Ucontext_1t_alignof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Signal_Ucontext_t
 * Method:    offsetof_Uc_sigmask
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Signal_00024Ucontext_1t_offsetof_1Uc_1sigmask
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Signal_Ucontext_t
 * Method:    offsetof_Uc_stack
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Signal_00024Ucontext_1t_offsetof_1Uc_1stack
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Signal_Ucontext_t
 * Method:    offsetof_Uc_mcontext
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Signal_00024Ucontext_1t_offsetof_1Uc_1mcontext
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Signal_Ucontext_t
 * Method:    uc_link0
 * Signature: ()Lde/ibapl/jnhw/common/memory/NativeAddressHolder;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_Signal_00024Ucontext_1t_uc_1link0
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
