/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_Termios_StructTermios */

#ifndef _Included_de_ibapl_jnhw_posix_Termios_StructTermios
#define _Included_de_ibapl_jnhw_posix_Termios_StructTermios
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_Termios_StructTermios
 * Method:    sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Termios_00024StructTermios_sizeof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Termios_StructTermios
 * Method:    alignof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Termios_00024StructTermios_alignof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Termios_StructTermios
 * Method:    c_iflag
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Termios_00024StructTermios_c_1iflag__
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Termios_StructTermios
 * Method:    c_iflag
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Termios_00024StructTermios_c_1iflag__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Termios_StructTermios
 * Method:    c_oflag
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Termios_00024StructTermios_c_1oflag__
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Termios_StructTermios
 * Method:    c_oflag
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Termios_00024StructTermios_c_1oflag__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Termios_StructTermios
 * Method:    c_cflag
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Termios_00024StructTermios_c_1cflag__
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Termios_StructTermios
 * Method:    c_cflag
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Termios_00024StructTermios_c_1cflag__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Termios_StructTermios
 * Method:    c_lflag
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Termios_00024StructTermios_c_1lflag__
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Termios_StructTermios
 * Method:    c_lflag
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Termios_00024StructTermios_c_1lflag__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Termios_StructTermios
 * Method:    c_cc
 * Signature: (I)B
 */
JNIEXPORT jbyte JNICALL Java_de_ibapl_jnhw_posix_Termios_00024StructTermios_c_1cc__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Termios_StructTermios
 * Method:    c_cc
 * Signature: (IB)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Termios_00024StructTermios_c_1cc__IB
  (JNIEnv *, jobject, jint, jbyte);

/*
 * Class:     de_ibapl_jnhw_posix_Termios_StructTermios
 * Method:    c_line
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_de_ibapl_jnhw_posix_Termios_00024StructTermios_c_1line__
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Termios_StructTermios
 * Method:    c_line
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Termios_00024StructTermios_c_1line__B
  (JNIEnv *, jobject, jbyte);

/*
 * Class:     de_ibapl_jnhw_posix_Termios_StructTermios
 * Method:    c_ispeed
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Termios_00024StructTermios_c_1ispeed__
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Termios_StructTermios
 * Method:    c_ispeed
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Termios_00024StructTermios_c_1ispeed__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Termios_StructTermios
 * Method:    c_ospeed
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Termios_00024StructTermios_c_1ospeed__
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Termios_StructTermios
 * Method:    c_ospeed
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Termios_00024StructTermios_c_1ospeed__I
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
