/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_Signal */

#ifndef _Included_de_ibapl_jnhw_posix_Signal
#define _Included_de_ibapl_jnhw_posix_Signal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    initFields
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_initFields
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    kill
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_kill
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    killpg
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_killpg
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    psiginfo
 * Signature: (Lde/ibapl/jnhw/posix/Signal/Siginfo_t;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_psiginfo
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    psignal
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_psignal
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    pthread_kill
 * Signature: (Lde/ibapl/jnhw/posix/Pthread/Pthread_t;I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_pthread_1kill
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    pthread_sigmask
 * Signature: (ILde/ibapl/jnhw/posix/Signal/Sigset_t;Lde/ibapl/jnhw/posix/Signal/Sigset_t;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_pthread_1sigmask
  (JNIEnv *, jclass, jint, jobject, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    raise
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_raise
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    sigaction
 * Signature: (ILde/ibapl/jnhw/posix/Signal/Sigaction;Lde/ibapl/jnhw/posix/Signal/Sigaction;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_sigaction
  (JNIEnv *, jclass, jint, jobject, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    sigaddset
 * Signature: (Lde/ibapl/jnhw/posix/Signal/Sigset_t;I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_sigaddset
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    sigaltstack
 * Signature: (Lde/ibapl/jnhw/posix/Signal/Stack_t;Lde/ibapl/jnhw/posix/Signal/Stack_t;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_sigaltstack
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    sigdelset
 * Signature: (Lde/ibapl/jnhw/posix/Signal/Sigset_t;I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_sigdelset
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    sigemptyset
 * Signature: (Lde/ibapl/jnhw/posix/Signal/Sigset_t;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_sigemptyset
  (JNIEnv *, jclass, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    sigfillset
 * Signature: (Lde/ibapl/jnhw/posix/Signal/Sigset_t;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_sigfillset
  (JNIEnv *, jclass, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    sighold
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_sighold
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    sigignore
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_sigignore
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    siginterrupt
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_siginterrupt
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    sigismember
 * Signature: (Lde/ibapl/jnhw/posix/Signal/Sigset_t;I)Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_posix_Signal_sigismember
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    signal
 * Signature: (ILde/ibapl/jnhw/common/nativepointer/FunctionPtr_I_V;)Lde/ibapl/jnhw/common/nativepointer/FunctionPtr_I_V;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_Signal_signal
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    sigpause
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_sigpause
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    sigpending
 * Signature: (Lde/ibapl/jnhw/posix/Signal/Sigset_t;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_sigpending
  (JNIEnv *, jclass, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    sigprocmask
 * Signature: (ILde/ibapl/jnhw/posix/Signal/Sigset_t;Lde/ibapl/jnhw/posix/Signal/Sigset_t;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_sigprocmask
  (JNIEnv *, jclass, jint, jobject, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    sigqueue
 * Signature: (IILde/ibapl/jnhw/posix/Signal/Sigval;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_sigqueue
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    sigrelse
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_sigrelse
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    sigset
 * Signature: (ILde/ibapl/jnhw/common/nativepointer/FunctionPtr_I_V;)Lde/ibapl/jnhw/common/nativepointer/FunctionPtr_I_V;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_Signal_sigset
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    sigsuspend
 * Signature: (Lde/ibapl/jnhw/posix/Signal/Sigset_t;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_sigsuspend
  (JNIEnv *, jclass, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    sigtimedwait
 * Signature: (Lde/ibapl/jnhw/posix/Signal/Sigset_t;Lde/ibapl/jnhw/posix/Signal/Siginfo_t;Lde/ibapl/jnhw/posix/Time/Timespec;)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Signal_sigtimedwait
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    sigwait
 * Signature: (Lde/ibapl/jnhw/posix/Signal/Sigset_t;)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Signal_sigwait
  (JNIEnv *, jclass, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    sigwaitinfo
 * Signature: (Lde/ibapl/jnhw/posix/Signal/Sigset_t;Lde/ibapl/jnhw/posix/Signal/Siginfo_t;)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Signal_sigwaitinfo
  (JNIEnv *, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
