/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_Aio */

#ifndef _Included_de_ibapl_jnhw_posix_Aio
#define _Included_de_ibapl_jnhw_posix_Aio
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_Aio
 * Method:    initFields
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Aio_initFields
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Aio
 * Method:    aio_cancel
 * Signature: (Lde/ibapl/jnhw/posix/Aio/Aiocb;)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Aio_aio_1cancel__Lde_ibapl_jnhw_posix_Aio_Aiocb_2
  (JNIEnv *, jclass, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Aio
 * Method:    aio_cancel
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Aio_aio_1cancel__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Aio
 * Method:    aio_error
 * Signature: (Lde/ibapl/jnhw/posix/Aio/Aiocb;)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Aio_aio_1error
  (JNIEnv *, jclass, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Aio
 * Method:    aio_fsync
 * Signature: (ILde/ibapl/jnhw/posix/Aio/Aiocb;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Aio_aio_1fsync
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Aio
 * Method:    aio_read
 * Signature: (Lde/ibapl/jnhw/posix/Aio/Aiocb;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Aio_aio_1read
  (JNIEnv *, jclass, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Aio
 * Method:    aio_return
 * Signature: (Lde/ibapl/jnhw/posix/Aio/Aiocb;)J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_Aio_aio_1return
  (JNIEnv *, jclass, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Aio
 * Method:    aio_suspend
 * Signature: (Lde/ibapl/jnhw/posix/Aio/Aiocbs;Lde/ibapl/jnhw/posix/Time/Timespec;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Aio_aio_1suspend
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Aio
 * Method:    aio_write
 * Signature: (Lde/ibapl/jnhw/posix/Aio/Aiocb;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Aio_aio_1write
  (JNIEnv *, jclass, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Aio
 * Method:    lio_listio
 * Signature: (ILde/ibapl/jnhw/posix/Aio/Aiocbs;Lde/ibapl/jnhw/posix/Signal/Sigevent;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Aio_lio_1listio
  (JNIEnv *, jclass, jint, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
