/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_Unistd_JnhwPrimitiveArrayCritical */

#ifndef _Included_de_ibapl_jnhw_posix_Unistd_JnhwPrimitiveArrayCritical
#define _Included_de_ibapl_jnhw_posix_Unistd_JnhwPrimitiveArrayCritical
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_Unistd_JnhwPrimitiveArrayCritical
 * Method:    read
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Unistd_00024JnhwPrimitiveArrayCritical_read
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Unistd_JnhwPrimitiveArrayCritical
 * Method:    write
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Unistd_00024JnhwPrimitiveArrayCritical_write
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
