/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_Time_Tm */

#ifndef _Included_de_ibapl_jnhw_posix_Time_Tm
#define _Included_de_ibapl_jnhw_posix_Time_Tm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_Time_Tm
 * Method:    sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Time_00024Tm_sizeof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Time_Tm
 * Method:    alignof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Time_00024Tm_alignof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Time_Tm
 * Method:    tm_sec
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Time_00024Tm_tm_1sec__
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Time_Tm
 * Method:    tm_min
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Time_00024Tm_tm_1min__
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Time_Tm
 * Method:    tm_hour
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Time_00024Tm_tm_1hour__
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Time_Tm
 * Method:    tm_mday
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Time_00024Tm_tm_1mday__
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Time_Tm
 * Method:    tm_mon
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Time_00024Tm_tm_1mon__
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Time_Tm
 * Method:    tm_year
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Time_00024Tm_tm_1year__
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Time_Tm
 * Method:    tm_wday
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Time_00024Tm_tm_1wday__
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Time_Tm
 * Method:    tm_yday
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Time_00024Tm_tm_1yday__
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Time_Tm
 * Method:    tm_isdst
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Time_00024Tm_tm_1isdst__
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Time_Tm
 * Method:    tm_sec
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Time_00024Tm_tm_1sec__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Time_Tm
 * Method:    tm_min
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Time_00024Tm_tm_1min__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Time_Tm
 * Method:    tm_hour
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Time_00024Tm_tm_1hour__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Time_Tm
 * Method:    tm_mday
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Time_00024Tm_tm_1mday__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Time_Tm
 * Method:    tm_mon
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Time_00024Tm_tm_1mon__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Time_Tm
 * Method:    tm_year
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Time_00024Tm_tm_1year__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Time_Tm
 * Method:    tm_wday
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Time_00024Tm_tm_1wday__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Time_Tm
 * Method:    tm_yday
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Time_00024Tm_tm_1yday__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Time_Tm
 * Method:    tm_isdst
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Time_00024Tm_tm_1isdst__I
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
