/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_Signal_Mcontext_t */

#ifndef _Included_de_ibapl_jnhw_posix_Signal_Mcontext_t
#define _Included_de_ibapl_jnhw_posix_Signal_Mcontext_t
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_Signal_Mcontext_t
 * Method:    sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Signal_00024Mcontext_1t_sizeof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Signal_Mcontext_t
 * Method:    alignof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Signal_00024Mcontext_1t_alignof
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
