/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_Pthread */

#ifndef _Included_de_ibapl_jnhw_posix_Pthread
#define _Included_de_ibapl_jnhw_posix_Pthread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_Pthread
 * Method:    initFields
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Pthread_initFields
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Pthread
 * Method:    pthread_self
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Pthread_pthread_1self
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_Pthread
 * Method:    pthread_equal
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_posix_Pthread_pthread_1equal
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_Pthread
 * Method:    pthread_attr_getinheritsched
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Pthread_pthread_1attr_1getinheritsched
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_Pthread
 * Method:    pthread_attr_getschedparam
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Pthread_pthread_1attr_1getschedparam
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_Pthread
 * Method:    pthread_attr_setinheritsched
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Pthread_pthread_1attr_1setinheritsched
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Pthread
 * Method:    pthread_attr_setschedparam
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Pthread_pthread_1attr_1setschedparam
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_Pthread
 * Method:    pthread_getschedparam
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Pthread_pthread_1getschedparam
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_Pthread
 * Method:    pthread_setschedparam
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Pthread_pthread_1setschedparam
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_Pthread
 * Method:    pthread_setschedprio
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Pthread_pthread_1setschedprio
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Pthread
 * Method:    pthread_getcpuclockid
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Pthread_pthread_1getcpuclockid
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_Pthread
 * Method:    pthread_attr_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Pthread_pthread_1attr_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_Pthread
 * Method:    pthread_attr_init
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Pthread_pthread_1attr_1init
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_Pthread
 * Method:    pthread_cancel
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Pthread_pthread_1cancel
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_Pthread
 * Method:    pthread_testcancel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Pthread_pthread_1testcancel
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Pthread
 * Method:    pthread_setcancelstate
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Pthread_pthread_1setcancelstate
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Pthread
 * Method:    pthread_setcanceltype
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Pthread_pthread_1setcanceltype
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
