/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_unix_sys_Ioctl */

#ifndef _Included_de_ibapl_jnhw_unix_sys_Ioctl
#define _Included_de_ibapl_jnhw_unix_sys_Ioctl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_unix_sys_Ioctl
 * Method:    _IOC
 * Signature: (ICII)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_unix_sys_Ioctl__1IOC
  (JNIEnv *, jclass, jint, jchar, jint, jint);

/*
 * Class:     de_ibapl_jnhw_unix_sys_Ioctl
 * Method:    _IO
 * Signature: (CI)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_unix_sys_Ioctl__1IO
  (JNIEnv *, jclass, jchar, jint);

/*
 * Class:     de_ibapl_jnhw_unix_sys_Ioctl
 * Method:    _IOC_DIR
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_unix_sys_Ioctl__1IOC_1DIR
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_ibapl_jnhw_unix_sys_Ioctl
 * Method:    _IOC_TYPE
 * Signature: (I)C
 */
JNIEXPORT jchar JNICALL Java_de_ibapl_jnhw_unix_sys_Ioctl__1IOC_1TYPE
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_ibapl_jnhw_unix_sys_Ioctl
 * Method:    _IOC_NR
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_unix_sys_Ioctl__1IOC_1NR
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_ibapl_jnhw_unix_sys_Ioctl
 * Method:    _IOC_SIZE
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_unix_sys_Ioctl__1IOC_1SIZE
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_ibapl_jnhw_unix_sys_Ioctl
 * Method:    IOCPARM_LEN
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_unix_sys_Ioctl_IOCPARM_1LEN
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_ibapl_jnhw_unix_sys_Ioctl
 * Method:    IOCBASECMD
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_unix_sys_Ioctl_IOCBASECMD
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_ibapl_jnhw_unix_sys_Ioctl
 * Method:    IOCGROUP
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_unix_sys_Ioctl_IOCGROUP
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_ibapl_jnhw_unix_sys_Ioctl
 * Method:    ioctl
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_unix_sys_Ioctl_ioctl__II
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     de_ibapl_jnhw_unix_sys_Ioctl
 * Method:    ioctl_ReturnValue
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_unix_sys_Ioctl_ioctl_1ReturnValue
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     de_ibapl_jnhw_unix_sys_Ioctl
 * Method:    ioctl
 * Signature: (IIJ)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_unix_sys_Ioctl_ioctl__IIJ
  (JNIEnv *, jclass, jint, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
