/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_StringHeader */

#ifndef _Included_de_ibapl_jnhw_posix_StringHeader
#define _Included_de_ibapl_jnhw_posix_StringHeader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_StringHeader
 * Method:    strerror
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_ibapl_jnhw_posix_StringHeader_strerror
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_ibapl_jnhw_posix_StringHeader
 * Method:    strerror_l
 * Signature: (IJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_ibapl_jnhw_posix_StringHeader_strerror_1l
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_StringHeader
 * Method:    strsignal
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_ibapl_jnhw_posix_StringHeader_strsignal
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
