/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_sys_Types */

#ifndef _Included_de_ibapl_jnhw_posix_sys_Types
#define _Included_de_ibapl_jnhw_posix_sys_Types
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_sys_Types
 * Method:    initFields
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_sys_Types_initFields
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
