/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_Pthread_Pthread_t */

#ifndef _Included_de_ibapl_jnhw_posix_Pthread_Pthread_t
#define _Included_de_ibapl_jnhw_posix_Pthread_Pthread_t
#ifdef __cplusplus
extern "C" {
#endif
#undef de_ibapl_jnhw_posix_Pthread_Pthread_t_NULL
#define de_ibapl_jnhw_posix_Pthread_Pthread_t_NULL 0LL
/*
 * Class:     de_ibapl_jnhw_posix_Pthread_Pthread_t
 * Method:    native2Layout
 * Signature: (Ljava/lang/Class;)Lde/ibapl/jnhw/posix/Pthread/Pthread_t/Layout;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_Pthread_00024Pthread_1t_native2Layout
  (JNIEnv *, jclass, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Pthread_Pthread_t
 * Method:    nativeToString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_ibapl_jnhw_posix_Pthread_00024Pthread_1t_nativeToString
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
