/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_Termios_StructTermios */

#ifndef _Included_de_ibapl_jnhw_posix_Termios_StructTermios
#define _Included_de_ibapl_jnhw_posix_Termios_StructTermios
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_Termios_StructTermios
 * Method:    native2Layout
 * Signature: (Ljava/lang/Class;)Lde/ibapl/jnhw/posix/Termios/StructTermios/Layout;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_Termios_00024StructTermios_native2Layout
  (JNIEnv *, jclass, jclass);

#ifdef __cplusplus
}
#endif
#endif
