/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_Aio_Aiocb */

#ifndef _Included_de_ibapl_jnhw_posix_Aio_Aiocb
#define _Included_de_ibapl_jnhw_posix_Aio_Aiocb
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_Aio_Aiocb
 * Method:    sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Aio_00024Aiocb_sizeof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Aio_Aiocb
 * Method:    alignof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Aio_00024Aiocb_alignof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Aio_Aiocb
 * Method:    offsetof_Aio_sigevent
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Aio_00024Aiocb_offsetof_1Aio_1sigevent
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Aio_Aiocb
 * Method:    aio_fildes
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Aio_00024Aiocb_aio_1fildes__
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Aio_Aiocb
 * Method:    aio_fildes
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Aio_00024Aiocb_aio_1fildes__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Aio_Aiocb
 * Method:    aio_offset
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_Aio_00024Aiocb_aio_1offset__
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Aio_Aiocb
 * Method:    aio_offset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Aio_00024Aiocb_aio_1offset__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_Aio_Aiocb
 * Method:    aio_buf0
 * Signature: ()Lde/ibapl/jnhw/common/memory/NativeAddressHolder;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_Aio_00024Aiocb_aio_1buf0
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Aio_Aiocb
 * Method:    aio_bufByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Aio_00024Aiocb_aio_1bufByteBuffer
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Aio_Aiocb
 * Method:    aio_bufOpaqueMemory
 * Signature: (Lde/ibapl/jnhw/common/memory/OpaqueMemory32;II)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Aio_00024Aiocb_aio_1bufOpaqueMemory
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Aio_Aiocb
 * Method:    aio_nbytes
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_Aio_00024Aiocb_aio_1nbytes
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Aio_Aiocb
 * Method:    aio_reqprio
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Aio_00024Aiocb_aio_1reqprio__
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Aio_Aiocb
 * Method:    aio_reqprio
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Aio_00024Aiocb_aio_1reqprio__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Aio_Aiocb
 * Method:    aio_lio_opcode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Aio_00024Aiocb_aio_1lio_1opcode__
  (JNIEnv *, jobject);

/*
 * Class:     de_ibapl_jnhw_posix_Aio_Aiocb
 * Method:    aio_lio_opcode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Aio_00024Aiocb_aio_1lio_1opcode__I
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
