/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_Signal */

#ifndef _Included_de_ibapl_jnhw_posix_Signal
#define _Included_de_ibapl_jnhw_posix_Signal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    initFields
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_initFields
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    kill
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_kill
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    killpg
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_killpg
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    psiginfo
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_psiginfo
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    psignal
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_psignal
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    pthread_kill
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_pthread_1kill
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    pthread_sigmask
 * Signature: (IJJ)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_pthread_1sigmask
  (JNIEnv *, jclass, jint, jlong, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    raise
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_raise
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    sigaction
 * Signature: (IJJ)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_sigaction
  (JNIEnv *, jclass, jint, jlong, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    sigaddset
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_sigaddset
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    sigaltstack
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_sigaltstack
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    sigdelset
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_sigdelset
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    sigemptyset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_sigemptyset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    sigfillset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_sigfillset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    sighold
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_sighold
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    sigignore
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_sigignore
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    siginterrupt
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_siginterrupt
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    sigismember
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_de_ibapl_jnhw_posix_Signal_sigismember
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    signal
 * Signature: (IJ)J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_Signal_signal
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    sigpause
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_sigpause
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    sigpending
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_sigpending
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    sigprocmask
 * Signature: (IJJ)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_sigprocmask
  (JNIEnv *, jclass, jint, jlong, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    sigqueue
 * Signature: (IIJ)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_sigqueue
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    sigrelse
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_sigrelse
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    sigset
 * Signature: (IJ)J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_posix_Signal_sigset
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    sigsuspend
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_posix_Signal_sigsuspend
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    sigtimedwait
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Signal_sigtimedwait
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    sigwait
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Signal_sigwait
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_ibapl_jnhw_posix_Signal
 * Method:    sigwaitinfo
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_posix_Signal_sigwaitinfo
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
