/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_posix_Sched_Sched_param */

#ifndef _Included_de_ibapl_jnhw_posix_Sched_Sched_param
#define _Included_de_ibapl_jnhw_posix_Sched_Sched_param
#ifdef __cplusplus
extern "C" {
#endif
#undef de_ibapl_jnhw_posix_Sched_Sched_param_NULL
#define de_ibapl_jnhw_posix_Sched_Sched_param_NULL 0LL
/*
 * Class:     de_ibapl_jnhw_posix_Sched_Sched_param
 * Method:    native2Layout
 * Signature: (Ljava/lang/Class;)Lde/ibapl/jnhw/posix/Sched/Sched_param/Layout;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_posix_Sched_00024Sched_1param_native2Layout
  (JNIEnv *, jclass, jclass);

#ifdef __cplusplus
}
#endif
#endif
