/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_util_posix_Callback__Sigval_int__V_Impl */

#ifndef _Included_de_ibapl_jnhw_util_posix_Callback__Sigval_int__V_Impl
#define _Included_de_ibapl_jnhw_util_posix_Callback__Sigval_int__V_Impl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_util_posix_Callback__Sigval_int__V_Impl
 * Method:    initNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_util_posix_Callback_1_1Sigval_1int_1_1V_1Impl_initNative
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_util_posix_Callback__Sigval_int__V_Impl
 * Method:    getNativeAddress
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_util_posix_Callback_1_1Sigval_1int_1_1V_1Impl_getNativeAddress
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_ibapl_jnhw_util_posix_Callback__Sigval_int__V_Impl
 * Method:    MAX_CALL_BACKS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_util_posix_Callback_1_1Sigval_1int_1_1V_1Impl_MAX_1CALL_1BACKS
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
