/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_test_references_IntRefTest */

#ifndef _Included_de_ibapl_jnhw_common_test_references_IntRefTest
#define _Included_de_ibapl_jnhw_common_test_references_IntRefTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_common_test_references_IntRefTest
 * Method:    testNative
 * Signature: (Lde/ibapl/jnhw/common/references/IntRef;I)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_common_test_references_IntRefTest_testNative
  (JNIEnv *, jclass, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
