/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_test_memory_layout_SimpeStructureImpl */

#ifndef _Included_de_ibapl_jnhw_common_test_memory_layout_SimpeStructureImpl
#define _Included_de_ibapl_jnhw_common_test_memory_layout_SimpeStructureImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_common_test_memory_layout_SimpeStructureImpl
 * Method:    getNativeDefinedLayout
 * Signature: (Ljava/lang/Class;)Lde/ibapl/jnhw/common/test/memory/layout/SimpeStructureImpl/Layout;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_common_test_memory_layout_SimpeStructureImpl_getNativeDefinedLayout
  (JNIEnv *, jclass, jclass);

#ifdef __cplusplus
}
#endif
#endif
