/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_test_callbacks_Callback_I_I_Mem_V_Test */

#ifndef _Included_de_ibapl_jnhw_common_test_callbacks_Callback_I_I_Mem_V_Test
#define _Included_de_ibapl_jnhw_common_test_callbacks_Callback_I_I_Mem_V_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_common_test_callbacks_Callback_I_I_Mem_V_Test
 * Method:    getCallbackPtr0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_common_test_callbacks_Callback_1I_1I_1Mem_1V_1Test_getCallbackPtr0
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_common_test_callbacks_Callback_I_I_Mem_V_Test
 * Method:    setCallback
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_common_test_callbacks_Callback_1I_1I_1Mem_1V_1Test_setCallback
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_ibapl_jnhw_common_test_callbacks_Callback_I_I_Mem_V_Test
 * Method:    doCallTheCallback
 * Signature: (IIJ)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_common_test_callbacks_Callback_1I_1I_1Mem_1V_1Test_doCallTheCallback
  (JNIEnv *, jclass, jint, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
