/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_test_callbacks_Callback_I_Mem_Mem_V_Test */

#ifndef _Included_de_ibapl_jnhw_common_test_callbacks_Callback_I_Mem_Mem_V_Test
#define _Included_de_ibapl_jnhw_common_test_callbacks_Callback_I_Mem_Mem_V_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_common_test_callbacks_Callback_I_Mem_Mem_V_Test
 * Method:    getCallbackPtr
 * Signature: ()Lde/ibapl/jnhw/common/nativepointer/FunctionPtr_I_Mem_Mem_V;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_common_test_callbacks_Callback_1I_1Mem_1Mem_1V_1Test_getCallbackPtr
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_common_test_callbacks_Callback_I_Mem_Mem_V_Test
 * Method:    setCallback
 * Signature: (Lde/ibapl/jnhw/common/callback/Callback_I_Mem_Mem_V;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_common_test_callbacks_Callback_1I_1Mem_1Mem_1V_1Test_setCallback
  (JNIEnv *, jclass, jobject);

/*
 * Class:     de_ibapl_jnhw_common_test_callbacks_Callback_I_Mem_Mem_V_Test
 * Method:    doCallTheCallback
 * Signature: (ILde/ibapl/jnhw/common/test/callbacks/Callback_I_Mem_Mem_V_Test/A;Lde/ibapl/jnhw/common/test/callbacks/Callback_I_Mem_Mem_V_Test/B;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_common_test_callbacks_Callback_1I_1Mem_1Mem_1V_1Test_doCallTheCallback
  (JNIEnv *, jclass, jint, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
