/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_test_memory_layout_StructLayoutTest */

#ifndef _Included_de_ibapl_jnhw_common_test_memory_layout_StructLayoutTest
#define _Included_de_ibapl_jnhw_common_test_memory_layout_StructLayoutTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_common_test_memory_layout_StructLayoutTest
 * Method:    createLayout
 * Signature: (Ljava/lang/Class;Ljava/lang/Class;JJLjava/lang/String;Ljava/lang/String;J)Lde/ibapl/jnhw/common/memory/layout/StructLayout;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_common_test_memory_layout_StructLayoutTest_createLayout
  (JNIEnv *, jclass, jclass, jclass, jlong, jlong, jstring, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
