/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_test_memory_PointerArray32Test */

#ifndef _Included_de_ibapl_jnhw_common_test_memory_PointerArray32Test
#define _Included_de_ibapl_jnhw_common_test_memory_PointerArray32Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_common_test_memory_PointerArray32Test
 * Method:    getCachedReferencesLength
 * Signature: (Lde/ibapl/jnhw/common/memory/PointerArray32;)I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_common_test_memory_PointerArray32Test_getCachedReferencesLength
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
