/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_test_callbacks_NativeRunnableTest */

#ifndef _Included_de_ibapl_jnhw_common_test_callbacks_NativeRunnableTest
#define _Included_de_ibapl_jnhw_common_test_callbacks_NativeRunnableTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_common_test_callbacks_NativeRunnableTest
 * Method:    getCallbackPtr0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_common_test_callbacks_NativeRunnableTest_getCallbackPtr0
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_common_test_callbacks_NativeRunnableTest
 * Method:    setCallback
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_common_test_callbacks_NativeRunnableTest_setCallback
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_ibapl_jnhw_common_test_callbacks_NativeRunnableTest
 * Method:    doCallTheCallback
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_common_test_callbacks_NativeRunnableTest_doCallTheCallback
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_ibapl_jnhw_common_test_callbacks_NativeRunnableTest
 * Method:    doCallRunnable
 * Signature: (Ljava/lang/Runnable;)V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_common_test_callbacks_NativeRunnableTest_doCallRunnable
  (JNIEnv *, jclass, jobject);

/*
 * Class:     de_ibapl_jnhw_common_test_callbacks_NativeRunnableTest
 * Method:    doCallTheWrongCallbackPtr
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_ibapl_jnhw_common_test_callbacks_NativeRunnableTest_doCallTheWrongCallbackPtr
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
