/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_test_memory_layout_FieldLayoutTest */

#ifndef _Included_de_ibapl_jnhw_common_test_memory_layout_FieldLayoutTest
#define _Included_de_ibapl_jnhw_common_test_memory_layout_FieldLayoutTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_common_test_memory_layout_FieldLayoutTest
 * Method:    createLayout
 * Signature: (Ljava/lang/Class;Ljava/lang/String;J)Lde/ibapl/jnhw/common/memory/layout/FieldLayout;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_common_test_memory_layout_FieldLayoutTest_createLayout
  (JNIEnv *, jclass, jclass, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
