/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_test_references_ByteRefTest */

#ifndef _Included_de_ibapl_jnhw_common_test_references_ByteRefTest
#define _Included_de_ibapl_jnhw_common_test_references_ByteRefTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_common_test_references_ByteRefTest
 * Method:    testNative
 * Signature: (Lde/ibapl/jnhw/common/references/ByteRef;B)B
 */
JNIEXPORT jbyte JNICALL Java_de_ibapl_jnhw_common_test_references_ByteRefTest_testNative
  (JNIEnv *, jclass, jobject, jbyte);

#ifdef __cplusplus
}
#endif
#endif
