/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_test_references_ObjectRefTest */

#ifndef _Included_de_ibapl_jnhw_common_test_references_ObjectRefTest
#define _Included_de_ibapl_jnhw_common_test_references_ObjectRefTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_common_test_references_ObjectRefTest
 * Method:    testNative
 * Signature: (Lde/ibapl/jnhw/common/references/ObjectRef;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_de_ibapl_jnhw_common_test_references_ObjectRefTest_testNative
  (JNIEnv *, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
