/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_test_references_LongRefTest */

#ifndef _Included_de_ibapl_jnhw_common_test_references_LongRefTest
#define _Included_de_ibapl_jnhw_common_test_references_LongRefTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_common_test_references_LongRefTest
 * Method:    testNative
 * Signature: (Lde/ibapl/jnhw/common/references/LongRef;J)J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_common_test_references_LongRefTest_testNative
  (JNIEnv *, jclass, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
