/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_test_datatypes_BaseDataTypeTest */

#ifndef _Included_de_ibapl_jnhw_common_test_datatypes_BaseDataTypeTest
#define _Included_de_ibapl_jnhw_common_test_datatypes_BaseDataTypeTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ibapl_jnhw_common_test_datatypes_BaseDataTypeTest
 * Method:    getSizeOfPointer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_common_test_datatypes_BaseDataTypeTest_getSizeOfPointer
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_common_test_datatypes_BaseDataTypeTest
 * Method:    getSizeOf_long
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_common_test_datatypes_BaseDataTypeTest_getSizeOf_1long
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_common_test_datatypes_BaseDataTypeTest
 * Method:    getSizeOf_float
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_common_test_datatypes_BaseDataTypeTest_getSizeOf_1float
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_common_test_datatypes_BaseDataTypeTest
 * Method:    getSizeOf_double
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_common_test_datatypes_BaseDataTypeTest_getSizeOf_1double
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_common_test_datatypes_BaseDataTypeTest
 * Method:    getSizeOf_long_double
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_common_test_datatypes_BaseDataTypeTest_getSizeOf_1long_1double
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
