/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ibapl_jnhw_common_test_memory_layout_SimpeStructureImpl */

#ifndef _Included_de_ibapl_jnhw_common_test_memory_layout_SimpeStructureImpl
#define _Included_de_ibapl_jnhw_common_test_memory_layout_SimpeStructureImpl
#ifdef __cplusplus
extern "C" {
#endif
#undef de_ibapl_jnhw_common_test_memory_layout_SimpeStructureImpl_NULL
#define de_ibapl_jnhw_common_test_memory_layout_SimpeStructureImpl_NULL 0LL
/*
 * Class:     de_ibapl_jnhw_common_test_memory_layout_SimpeStructureImpl
 * Method:    offsetFirst
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_common_test_memory_layout_SimpeStructureImpl_offsetFirst
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_common_test_memory_layout_SimpeStructureImpl
 * Method:    offsetSecond
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_common_test_memory_layout_SimpeStructureImpl_offsetSecond
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_common_test_memory_layout_SimpeStructureImpl
 * Method:    offsetThird
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_common_test_memory_layout_SimpeStructureImpl_offsetThird
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_common_test_memory_layout_SimpeStructureImpl
 * Method:    offsetForth
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_common_test_memory_layout_SimpeStructureImpl_offsetForth
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_common_test_memory_layout_SimpeStructureImpl
 * Method:    offsetFifth
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_common_test_memory_layout_SimpeStructureImpl_offsetFifth
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_common_test_memory_layout_SimpeStructureImpl
 * Method:    offsetSixth
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_common_test_memory_layout_SimpeStructureImpl_offsetSixth
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_common_test_memory_layout_SimpeStructureImpl
 * Method:    offsetSeventh
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_common_test_memory_layout_SimpeStructureImpl_offsetSeventh
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_common_test_memory_layout_SimpeStructureImpl
 * Method:    offsetEigth
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_ibapl_jnhw_common_test_memory_layout_SimpeStructureImpl_offsetEigth
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_common_test_memory_layout_SimpeStructureImpl
 * Method:    sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_common_test_memory_layout_SimpeStructureImpl_sizeof
  (JNIEnv *, jclass);

/*
 * Class:     de_ibapl_jnhw_common_test_memory_layout_SimpeStructureImpl
 * Method:    alignof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_ibapl_jnhw_common_test_memory_layout_SimpeStructureImpl_alignof
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
